IF
 Global("GLOBAL_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("GLOBAL_init","GLOBAL",1)
 
 Createcreature("COISLEN",[1690.1160],10)   
 Createcreature("COBASIL1",[1310.1005],10)    
 Createcreature("COBATIN",[200.240],10) 
 Createcreature("COBATIN",[160.235],10) 
 Createcreature("COBATIN",[1530.350],10) 
 Createcreature("COBATIN",[1380.920],10) 
 Createcreature("COBATIN",[900.640],10) 
 Createcreature("COBATIN",[340.680],10) 
 Createcreature("COBATIN",[460.990],10) 
 Createcreature("COBATIN",[1190.140],10) 
 Createcreature("COBATIN",[750.1200],10) 
 
 Wait(3)
 DisplaystringHead("COISLEN",@1)
  
 CloseDoor("GRILLE1")
 Lock("GRILLE1")
 TriggerActivation("COM021",FALSE)
 SetGlobal("Acces_COM021","GLOBAL",1)    
 
 CloseDoor("GRILLE2")
 Lock("GRILLE2")
 TriggerActivation("COM019",FALSE)  
 SetGlobal("Acces_COM019","GLOBAL",1) 
 
 SetGlobalTimer("T_COISLEN_chasse","GLOBAL",1) 
END


// Islendra est en chasse et elle poursuit quelqu'un à l'étage supérieur: arrêt de la chasse et redescente aussitôt ********************************************************
IF
 Global("COM020_COISLEN_DESC","GLOBAL",1)
THEN 
 RESPONSE #100
 SetGlobal("COM020_COISLEN_DESC","GLOBAL",0)
 CreateCreature("COISLEN",[1160.125],15)
END


// Islendra gestion de la chasses ******************************************************************************************************************
IF
 GlobalTimerExpired("T_COISLEN_chasse","GLOBAL")
 Global("COISLEN_chasse","GLOBAL",1)
 OR(6)
  AreaCheckObject("COM020",PLAYER1)
  AreaCheckObject("COM020",PLAYER2)
  AreaCheckObject("COM020",PLAYER3)
  AreaCheckObject("COM020",PLAYER4)
  AreaCheckObject("COM020",PLAYER5)
  AreaCheckObject("COM020",PLAYER6)
THEN
 RESPONSE #100
 ClearActions("COISLEN")
 SetGlobal("COISLEN_chasse","GLOBAL",2)
 
 Createcreature("MINSC",[400.450],10)  
END



/*
//  Arrivée d'un Player et début de la chasse *****************************************************************************************************************************
IF
 Global("sous_sol_ferme","GLOBAL",0)
THEN
  RESPONSE #100
  SetGlobal("sous_sol_ferme","GLOBAL",1)
  
  SetGlobalTimer("T_COISLEN_chasse","GLOBAL",1)
  
  Wait(3)
  //DisplaystringHead("COISLEN",@1)
  
  CloseDoor("GRILLE1")
  Lock("GRILLE1")
  TriggerActivation("COM021",FALSE)
  SetGlobal("Acces_COM021","GLOBAL",1)    
  
  CloseDoor("GRILLE2")
  Lock("GRILLE2")
  TriggerActivation("COM019",FALSE)  
  SetGlobal("Acces_COM019","GLOBAL",1)    
END




// Islendra détecte la présence d'intrus *************************************************************************************************************************************
IF 
 Global("GLOBAL_intrus","COM020",0)
 OR(6)
  AreaCheckObject("COM020",PLAYER1)
  AreaCheckObject("COM020",PLAYER2)
  AreaCheckObject("COM020",PLAYER3)
  AreaCheckObject("COM020",PLAYER4)
  AreaCheckObject("COM020",PLAYER5)
  AreaCheckObject("COM020",PLAYER6)
THEN
 RESPONSE #100
 SetGlobal("GLOBAL_intrus","COM020",1) // ~Vous êtes ici sur mon territoire de chasse. Partez imédiatement!~

 Wait(3)
 DisplaystringHead("COISLEN",@1)
 // sound
END
*/




// Téléportation duel Islendra ****************************************************************************************************************************************************
IF
 Global("COM020_PNJ_capture","GLOBAL",1)
 AreaCheckObject("COM020","COISLEN") 
THEN
 RESPONSE #100
 SetGlobal("COM020_PNJ_capture","GLOBAL",2)
 

 ActionOverride("COISLEN",DestroyItem("arop01"))
 //CreateVisualEffectObject("SPMAZE1",Lastseenby("COISLEN"))
 Wait(1)
 ActionOverride(Lastseenby("COISLEN"),JumpToPoint([360.665])) // Téléportation de la cible  
END

// Arrivée de Islendra à son tour
IF
 Global("COM020_PNJ_capture","GLOBAL",2)
 AreaCheckObject("COM020","COISLEN") 
THEN
 RESPONSE #100
 SetGlobal("COM020_PNJ_capture","GLOBAL",3)
 
 Createcreature("MINSC",[360.665],10)  
 
 
 CreateVisualEffectObject("SPMAZE1","COISLEN")
 Wait(1)
 ActionOverride("COISLEN",JumpToPoint([250.825]))
END 

// Arrivée de Islendra à son tour
IF
 Global("COM020_PNJ_capture","GLOBAL",2)
 !AreaCheckObject("COM020","COISLEN") 
THEN
 RESPONSE #100
 SetGlobal("COM020_PNJ_capture","GLOBAL",3)
 
 Createcreature("MINSC",[360.665],10) 
 Createcreature("MINSC",[360.665],10) 
 
 CreateVisualEffectObject("SPMAZE1","COISLEN")
 Wait(1)
 ActionOvErride("COISLEN",LeaveAreaLUA("COM020","",[250.825],1))
END 

// Glabuk apparait dans la zone de duel 
IF
 Global("Glabuk_apparition","GLOBAL",1)
 AreaCheckObject("COM020","COISLEN") 
THEN
 RESPONSE #100
 SetGlobal("Glabuk_apparition","GLOBAL",2)
 
 ActionOverride("cobasil1",JumpToPoint([250.825]))
 ForceSpell("cobasil1",GREY_MUSHROOM)
END


// Gestion de la corde **********************************************************************************************************************************************************************
// La corde a été lancée du niveau sup, on peut grimper à la corde qui est visible.
IF 
 Global("Corde_lancee1","GLOBAL",1)
 Global("Corde_grimper1","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper1","GLOBAL",1)
 
 // Gestion graphique 
 closeDoor("CORD1")
   
 // Activation gestion de la corde
 TriggerActivation("COT020C1",TRUE)
END

IF 
 Global("Corde_lancee2","GLOBAL",1)
 Global("Corde_grimper2","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper2","GLOBAL",1)
 
 // Gestion graphique 
 closeDoor("CORD2")
   
 // Activation gestion de la corde
 TriggerActivation("Cot020c2",TRUE)
END

IF 
 Global("Corde_lancee3","GLOBAL",1)
 Global("Corde_grimper3","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper3","GLOBAL",1)
 
 // Gestion graphique 
 closeDoor("CORD3")
   
 // Activation gestion de la corde
 TriggerActivation("COT020C3",TRUE)
END

IF 
 Global("Corde_lancee4","GLOBAL",1)
 Global("Corde_grimper4","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper4","GLOBAL",1)
 
 // Gestion graphique 
 closeDoor("CORD4")
   
 // Activation gestion de la corde
 TriggerActivation("COT020C4",TRUE)
END

IF 
 Global("Corde_lancee5","GLOBAL",1)
 Global("Corde_grimper5","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper5","GLOBAL",1)
 
 // Gestion graphique 
 closeDoor("CORD5")
   
 // Activation gestion de la corde
 TriggerActivation("COT020C5",TRUE)
END

// Un PLAYER monte à la corde mais n'est pas assez doué. Il chute.
IF
 Global("Corde_chuter_player","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Corde_chuter_player","GLOBAL",0) 
 ActionOverride(PLAYER1,PlayDead(100))
END

IF
 Global("Corde_chuter_player","GLOBAL",2)
THEN
 RESPONSE #100
 SetGlobal("Corde_chuter_player","GLOBAL",0) 
 ActionOverride(PLAYER2,PlayDead(100))
END

IF
 Global("Corde_chuter_player","GLOBAL",3)
THEN
 RESPONSE #100
 SetGlobal("Corde_chuter_player","GLOBAL",0) 
 ActionOverride(PLAYER3,PlayDead(100))
END

IF
 Global("Corde_chuter_player","GLOBAL",4)
THEN
 RESPONSE #100
 SetGlobal("Corde_chuter_player","GLOBAL",0) 
 ActionOverride(PLAYER4,PlayDead(100))
END

IF
 Global("Corde_chuter_player","GLOBAL",5)
THEN
 RESPONSE #100
 SetGlobal("Corde_chuter_player","GLOBAL",0) 
 ActionOverride(PLAYER5,PlayDead(100))
END

IF
 Global("Corde_chuter_player","GLOBAL",6)
THEN
 RESPONSE #100
 SetGlobal("Corde_chuter_player","GLOBAL",0) 
 ActionOverride(PLAYER6,PlayDead(100))
END

// La corde est retirée, on ne peut plus grimper. La corde n'est plus visible
IF 
 Global("Corde_lancee1","GLOBAL",0)
 Global("Corde_grimper1","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper1","GLOBAL",0)
 
 // Gestion graphique 
 OpenDoor("CORD1")
   
 // Activation gestion de la corde
 TriggerActivation("COT020C1",FALSE)
END

IF 
 Global("Corde_lancee2","GLOBAL",0)
 Global("Corde_grimper2","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper2","GLOBAL",0)
 
 // Gestion graphique 
 OpenDoor("CORD2")
   
 // Activation gestion de la corde
 TriggerActivation("COT020C2",FALSE)
END

IF 
 Global("Corde_lancee3","GLOBAL",0)
 Global("Corde_grimper3","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper3","GLOBAL",0)
 
 // Gestion graphique 
 OpenDoor("CORD3")
  
 CreateCreature("COMONK1",[460.410],10) 
  
 // Activation gestion de la corde
 TriggerActivation("COT020C2",FALSE)
END

IF 
 Global("Corde_lancee4","GLOBAL",0)
 Global("Corde_grimper4","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper4","GLOBAL",0)
 
 // Gestion graphique 
 OpenDoor("CORD4")
   
 // Activation gestion de la corde
 TriggerActivation("COT020C4",FALSE)
END

IF 
 Global("Corde_lancee5","GLOBAL",0)
 Global("Corde_grimper5","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Corde_grimper5","GLOBAL",0)
 
 // Gestion graphique 
 OpenDoor("CORD5")
   
 // Activation gestion de la corde
 TriggerActivation("COT020C5",FALSE)
END


// Gestion des ennemis trombés dans le trou (Elementaux ou le sorcier): apparition de l'ennemi ***************************************************************************
// Trappe1
IF 
 Global("Chute_ELE_AIR1","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_AIR1","GLOBAL",0)
 
 CreateCreature("COELAIR1",[140.655],10)  
END

IF 
 Global("Chute_ELE_TER1","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_TER1","GLOBAL",0)
 
 CreateCreature("ELEARL01",[140.655],10)  
END

IF 
 Global("Chute_ELE_FEU1","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_FEU1","GLOBAL",0)
 
 CreateCreature("ELEFEL01",[140.655],10)  
END

IF 
 Global("Chute_ELE_WAT1","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_WAT1","GLOBAL",0)
 
 CreateCreature("COELWAT1",[140.655],10)  
END

IF 
 Global("Chute_monk1","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_monk1","GLOBAL",0)
 
 CreateCreature("COMONK1",[140.655],10)  
END

IF 
 Global("Chute_serpent1","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_serpent1","GLOBAL",0)
 
 CreateCreature("COSNAK1",[140.655],10)  
END

// Trappe2
IF 
 Global("Chute_ELE_AIR2","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_AIR2","GLOBAL",0)
 
 CreateCreature("COELAIR1",[460.410],10)  
END

IF 
 Global("Chute_ELE_TER2","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_TER2","GLOBAL",0)
 
 CreateCreature("ELEARL01",[460.410],10)  
END

IF 
 Global("Chute_ELE_FEU2","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_FEU2","GLOBAL",0)
 
 CreateCreature("ELEFEL01",[460.410],10)  
END

IF 
 Global("Chute_ELE_WAT2","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_WAT2","GLOBAL",0)
 
 CreateCreature("COELWAT1",[460.410],10)  
END

IF 
 Global("Chute_monk2","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_monk2","GLOBAL",0)
 
 CreateCreature("COMONK1",[460.410],10)  
END

IF 
 Global("Chute_serpent2","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_serpent2","GLOBAL",0)
 
 CreateCreature("COSNAK1",[460.410],10)   
END


// Trappe3
IF 
 Global("Chute_ELE_AIR3","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_AIR3","GLOBAL",0)
 
 CreateCreature("COELAIR1",[335.520],10)  
END

IF 
 Global("Chute_ELE_TER3","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_TER3","GLOBAL",0)
 
 CreateCreature("ELEARL01",[335.520],10)  
END

IF 
 Global("Chute_ELE_FEU3","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_FEU3","GLOBAL",0)
 
 CreateCreature("ELEFEL01",[335.520],10)  
END

IF 
 Global("Chute_ELE_WAT3","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_WAT3","GLOBAL",0)
 
 CreateCreature("COELWAT1",[335.520],10)  
END

IF 
 Global("Chute_monk","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_monk3","GLOBAL",0)
 
 CreateCreature("COMONK1",[335.520],10)  
END

IF 
 Global("Chute_serpent3","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_serpent3","GLOBAL",0)
 
 CreateCreature("COSNAK1",[335.520],10)   
END


// Trappe4
IF 
 Global("Chute_ELE_AIR4","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_AIR4","GLOBAL",0)
 
 CreateCreature("COELAIR1",[1060.730],10)  
END

IF 
 Global("Chute_ELE_TER4","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_TER4","GLOBAL",0)
 
 CreateCreature("ELEARL01",[1060.730],10)  
END

IF 
 Global("Chute_ELE_FEU4","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_FEU4","GLOBAL",0)
 
 CreateCreature("ELEFEL01",[1060.730],10)  
END

IF 
 Global("Chute_ELE_WAT4","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_WAT4","GLOBAL",0)
 
 CreateCreature("COELWAT1",[1060.730],10)  
END

IF 
 Global("Chute_monk4","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_monk4","GLOBAL",0)
 
 CreateCreature("COMONK1",[1060.730],10)  
END

IF 
 Global("Chute_serpent4","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_serpent4","GLOBAL",0)
 
 CreateCreature("COSNAK1",[1060.730],10)   
END

// Trappe5
IF 
 Global("Chute_ELE_AIR5","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_AIR5","GLOBAL",0)
 
 CreateCreature("COELAIR1",[455.960],10)  
END

IF 
 Global("Chute_ELE_TER5","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_TER5","GLOBAL",0)
 
 CreateCreature("ELEARL01",[455.960],10)  
END

IF 
 Global("Chute_ELE_FEU5","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_FEU5","GLOBAL",0)
 
 CreateCreature("ELEFEL01",[455.960],10)  
END

IF 
 Global("Chute_ELE_WAT5","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_ELE_WAT5","GLOBAL",0)
 
 CreateCreature("COELWAT1",[455.960],10)  
END

IF 
 Global("Chute_monk5","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_monk5","GLOBAL",0)
 
 CreateCreature("COMONK1",[455.960],10)  
END

IF 
 Global("Chute_serpent5","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Chute_serpent5","GLOBAL",0)
 
 CreateCreature("COSNAK1",[455.960],10)     
END




  // Test
 /*
 closeDoor("CORD1") 
 closeDoor("CORD2") 
 closeDoor("CORD3") 
 closeDoor("CORD4") 
 closeDoor("CORD5") 
  

 SetGlobal("Corde_lancee2","GLOBAL",1)
 SetGlobal("Corde_lancee3","GLOBAL",1)
 SetGlobal("Corde_lancee4","GLOBAL",1)
 SetGlobal("Corde_lancee5","GLOBAL",1)
 
 
 Wait(10)
 //Createcreature("MINSC",[400.450],10) 
 ForceSpell("MINSC",GREY_MUSHROOM) 
 wait(4)
 //Createcreature("MINSC",[400.450],10) 
 ForceSpellRes("SPCL228","MINSC")
 wait(4)
 */
 
 /*
// ReOuverture des portes car il n'y avait plus de players
IF
 Global("sous_sol_ferme","GLOBAL",5)
THEN
  RESPONSE #100
  SetGlobal("sous_sol_ferme","GLOBAL",0)
  
  Unlock("GRILLE1")
  OpenDoor("GRILLE1")
  TriggerActivation("COM020",TRUE)
  
  Unlock("GRILLE2")
  OpenDoor("GRILLE2")
  TriggerActivation("COM019",TRUE)  
END
*/