// Les restes de Massena sont placés dans le sarcophage
IF
  Contains("SKELP01","Sarco1")
  Global("Massena_sarco_restes","Global",0)
THEN
  RESPONSE #100
  SetGlobal("Massena_sarco_restes","Global",1)
  ContainerEnable("Sarco1",FALSE)	 
  TriggerActivation("Sarco2",TRUE)  
  PlaySound("EFF_P90")
  wait(2)
  
  Createcreature("COMASSE1",[450.250],4)   
  smallwait(10)
  ActionOverride("COMASSE1",FaceObject([PC]))
  smallwait(10)
  ActionOverride("COMASSE1",SetDialogue("COMASSE2"))
  wait(1)
  ActionOverride("COMASSE1",StartDialogueNoSet([PC])) 
END

// Livre d'Ekilis en possession du groupe ou révelation d'Ekilis: evolution histoire du temple + trésors de Bhaal ******************************************************************************
IF
 Global("livre_ekilis","GLOBAL",0) 
 PartyHasItemIdentified("BOKP07")
THEN
 RESPONSE #100
 SetGlobal("livre_ekilis","GLOBAL",1)
 SetGlobal("Q_tresor_bhaal","GLOBAL",1) 
  
 // Histoire de Bhaal
 AddJournalEntry(@6,QUEST)   
END

IF
 Global("Q_tresor_bhaal","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Q_tresor_bhaal","GLOBAL",2) 

 // Le trésor de Bhaal 
 EraseJournalEntry(@50)
 EraseJournalEntry(@51)
 EraseJournalEntry(@52)
 EraseJournalEntry(@53)
 EraseJournalEntry(@54)
 AddJournalEntry(@55,QUEST_DONE)   
 AddXpObject(PLAYER1,500)
END


// Ekilis devient l'allié du groupe: il sera dans chaque carte où le PNJ qu'il suit prend une sortie
// Exception carte COM015: la grande grille (COM015) doit être ouverte
IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM016","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM016",PLAYER1)
  !Global("ekilis_follow","GLOBAL",0)
  Global("COM015_grille","GLOBAL",1)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER1)
  
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END


// DLG Massena terminé
IF
 Global("ekilis_deactivate","Global",1)
THEN
 RESPONSE #100
 SetGlobal("ekilis_deactivate","Global",0)
 Deactivate("COMASSE1")
END

// info dial avec Massena ***********************************************************************************************************************************************
// Quête réalisée: restes déposés dans le sarcophage
IF
 Global("quete_restes_sarco","COM016",0)
 Global("Massena_sarcophage","Global",2)
 Global("MF_temple_bhaal","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("quete_restes_sarco","COM016",1)
 
 EraseJournalEntry(@63)
 EraseJournalEntry(@64)
 EraseJournalEntry(@65)
 EraseJournalEntry(@66)
 EraseJournalEntry(@67)
 AddJournalEntry(@68,QUEST_DONE)   
 AddexperienceParty(1000)
END

IF
 Global("quete_restes_sarco","COM016",0)
 Global("Massena_sarcophage","Global",2)
 Global("MF_temple_bhaal","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("quete_restes_sarco","COM016",1)
 
 EraseJournalEntry(@63)
 EraseJournalEntry(@64)
 EraseJournalEntry(@65)
 EraseJournalEntry(@66)
 EraseJournalEntry(@67)
 AddJournalEntry(@80,QUEST_DONE)   
 AddexperienceParty(1000)
END

// info sortir d'ici
IF
 Global("quete_sortir_ici","GLOBAL",0)
 Global("Massena_sarcophage","Global",2)
 Global("MF_temple_bhaal","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("quete_sortir_ici","GLOBAL",1)
 AddJournalEntry(@71,QUEST)
END

// info histoire temple1
IF
 Global("hist_temple","COM016",1)
 Global("Massena_sarcophage","Global",2)
 Global("MF_temple_bhaal","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("hist_temple","COM016",2)
 AddJournalEntry(@69,QUEST)
END

// info histoire temple2
IF
 Global("hist_curieux","COM016",1)
 Global("Massena_sarcophage","Global",2)
 Global("MF_temple_bhaal","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("hist_curieux","COM016",2)
 AddJournalEntry(@70,QUEST)
END

// Le groupe prend les restes de Massena dans son équipement: le collier de massena apparait dans l'équipement ***********************************************************
IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER1)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER1,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER2)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER2,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER3)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER3,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER4)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER4,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER5)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER5,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER6)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER6,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

// Le cadavre n'est plus dans l'équipement du groupe: le collier disparait.
IF
 !PartyHasItem("Skelp01")
 PartyHasItem("AMUP02") 
 Global("collier_massena_init","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",0)
 TakePartyItem("AMUP02")
 /*
 wait(3)
 Actionoverride("COMASSE1",TakePartyItem("AMUP02"))
 */
END




// Ekilis en vie et le cadavre a été déposé dans le sarcophage: Massena est faché *********************************************************************
IF 
 Global("MF_temple_bhaal","GLOBAL",1)
THEN
 RESPONSE #100 
 SetGlobal("MF_temple_bhaal","GLOBAL",2)
 Deactivate("COMASSE1")
 
 Createcreature("MISTPO01",[316.289],10) 
 SmallWait(10)
 GiveItemCreate("COKEY01","MISTPO01",1,1,0) 
 
 Createcreature("GIBBER_P",[314.516],10) 
 Createcreature("GIBBER_P",[314.500],10) 
 Createcreature("GIBBER_P",[300.516],10) 
END
// FIN Mort fatale *********************************************************************



