IF
 Global("com017_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("com017_init","GLOBAL",1)
 
 Createcreature("COSYSTE",[1450.390],1) 
 
 CloseDoor("DOOR0004")  // Couloir avec champ de force
 CloseDoor("DOOR0005")  // Grille 
 
 CloseDoor("DOOR0001") // container secret
 CloseDoor("DOOR0002") // container secret
 ContainerEnable("Con01701",FALSE)	// Containers salle de réunion
 ContainerEnable("Con01702",FALSE) 
 ContainerEnable("Con017CF",FALSE) // Container crâne de feu
  
 // Containers salle réunion 
 TriggerActivation("COT017C1",TRUE) // champ de force salle puit
 TriggerActivation("COT017C2",FALSE) // champ de force salle puit
 TriggerActivation("COT01717",TRUE)
  
 // Sarcophages fermés 
 ContainerEnable("Con017s1",FALSE)
 ContainerEnable("Con017s2",FALSE)
 ContainerEnable("Con017s3",FALSE)
 ContainerEnable("Con017s4",FALSE)
 ContainerEnable("Con017s5",FALSE)
 ContainerEnable("Con017s6",FALSE)
 ContainerEnable("Con017s7",FALSE)
 ContainerEnable("Con017s8",FALSE)
 
 // Point info Sarcophages activés
 TriggerActivation("Cot017s1",TRUE)
 TriggerActivation("Cot017s2",TRUE)
 TriggerActivation("Cot017s3",TRUE)
 TriggerActivation("Cot017s4",TRUE)
 TriggerActivation("Cot017s5",TRUE)
 TriggerActivation("Cot017s6",TRUE)
 TriggerActivation("Cot017s7",TRUE)
 TriggerActivation("Cot017s8",TRUE) 

 // TEST
 //SetGlobal("massena_mort","Global",1) 
 //Createcreature("COEKILIS",[3000.900],10)
 //SetGlobal("Massena_sarcophage","GLOBAL",2)
  
  /*
 SetGlobal("ekilis_alliance","GLOBAL",1)
 SetGlobal("ekil_alli_follow_init","GLOBAL",0)
 SetGlobal("ekilis_init","GLOBAL",1)
 */
END

// Livre d'Ekilis en possession du groupe ou révelation d'Ekilis: evolution histoire du temple + trésors de Bhaal ******************************************************************************
IF
 Global("livre_ekilis","GLOBAL",0) 
 PartyHasItemIdentified("BOKP07")
THEN
 RESPONSE #100
 SetGlobal("livre_ekilis","GLOBAL",1)
 SetGlobal("Q_tresor_bhaal","GLOBAL",1) 
  
 // Histoire de Bhaal
 AddJournalEntry(@51,QUEST)   
END

IF
 Global("Q_tresor_bhaal","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Q_tresor_bhaal","GLOBAL",2) 

 // Le trésor de Bhaal 
 EraseJournalEntry(@53)
 EraseJournalEntry(@54)
 EraseJournalEntry(@55)
 EraseJournalEntry(@56)
 EraseJournalEntry(@57)
 AddJournalEntry(@58,QUEST_DONE)   
 AddXpObject(PLAYER1,1000)
END


// Ekilis révèle son identité et son désir de détruire Bhaal avec son crâne violet
IF 
 Global("revelation_ekilis","GLOBAL",1) 
THEN
 RESPONSE #100
 SetGlobal("revelation_ekilis","GLOBAL",2) 
 SetGlobal("Q_tresor_bhaal","GLOBAL",1) 
 
 // Histoire de Bhaal
 AddJournalEntry(@52,QUEST)   
END


// Le sort incanté (non terminé) et Ekilis meurt: Bhaal n'apparait pas *********************************************************************************
IF
 Dead("COEKILIS")
 Global("Bhaal_mort","GLOBAL",0) 
 Global("Ekilis_incantation_Bhaal","GLOBAL",2)
THEN
 RESPONSE #100
 SetGlobal("Bhaal_mort","GLOBAL",1) 
 
 DeActivate("COBHAAL") 
END

// La grille s'ouvre lorsque les épreuves peuvent commencer *******************************************************************************************************
// Ekilis et Massena sont morts, la textScreen a été lancée.
IF
 Global("grille_epreuves","GLOBAL",0)
 Global("ekilis_mort","Global",1)
 Global("TEXT_SCREEN_PUIT","GLOBAL",1)
 OR(2)
  Global("massena_mort","Global",1)
  GlobalGT("Massena_reste_brule","GLOBAL",1)
THEN
 RESPONSE #100 
 SetGlobal("grille_epreuves","GLOBAL",1)
 
 Wait(3)

 PlaySound("EFF_E01")
 UnLock("DOOR0006")
 OpenDoor("DOOR0006") 
 
 Wait(5)
 
 Unlock("DOOR0004")
 OpenDoor("DOOR0004") 
 
 //Createcreature("MINSC",[3700.900],10) 
END

// Le charname accepte l'épreuve de Bhaal: la grille s'ouvre.
IF
 Global("grille_epreuves","GLOBAL",0) 
 Global("Bhaal_epreuves","GLOBAL",1)
THEN
 RESPONSE #100 
 SetGlobal("grille_epreuves","GLOBAL",1)
 
 Wait(3)

 PlaySound("EFF_E01")
 UnLock("DOOR0006")
 OpenDoor("DOOR0006") 
 
 Wait(5)
 
 Unlock("DOOR0004")
 OpenDoor("DOOR0004")
END


// Crane de Kept placé: arrêt des pièges et ouverture des portes du temple *************************************************************************************************
IF
 Global("Crane_place","GLOBAL",0)
 Contains("MISCP62","Con017ck") 
 Global("Massena_sarcophage","Global",2)
THEN
 RESPONSE #100
 SetGlobal("Crane_place","GLOBAL",1)
 
 PlaySound("EFF_E01")
 AddJournalEntry(@60,QUEST) 
END

IF
 Global("Crane_place","GLOBAL",0)
 Contains("MISCP62","Con017ck") 
 !Global("Massena_sarcophage","Global",2)
THEN
 RESPONSE #100
 SetGlobal("Crane_place","GLOBAL",1)
 
 PlaySound("EFF_E01")
END

IF
 Global("Crane_place","GLOBAL",1)
 !Contains("MISCP62","Con017ck") 
THEN
 RESPONSE #100
 SetGlobal("Crane_place","GLOBAL",0)
 
 PlaySound("EFF_E04")
END

// Ekilis devient l'allié du groupe: il sera dans chaque carte où le PNJ qu'il suit prend une sortie ***********************************************************************
IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM017","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM017",PLAYER1)
  Global("ekilis_follow","GLOBAL",1)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER1)
  
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

// TEXTSCREEN: Le puit communique avec le Charname suite à son arrivée ****************************************************************************************************
IF
 GlobalTimerExpired("Puit_combat_t","GLOBAL")
 Global("TEXT_SCREEN_PUIT","GLOBAL",0) 
 OR(3)
  Global("MASSENA_PUIT_INIT","GLOBAL",2)
  Global("COEKILIS_PUIT_INIT","GLOBAL",2)
  Global("CHARNAME_PUIT_INIT","GLOBAL",1) 
THEN
 RESPONSE #100 
 SetGlobal("TEXT_SCREEN_PUIT","GLOBAL",1)
 SetGlobal("Puit_combat","GLOBAL",2) 
 
 Createcreature("TEST",[3700.600],10) 

 TEXTSCREEN("COTS007")
 DisplayStringHead(PLAYER1,@6) 
END


//  salle de réunion: Containers 1 découvert
IF
  OpenState("DOOR0001",TRUE)		
  Global("cont01701_init","GLOBAL",0)
THEN
  RESPONSE #100
  SetGlobal("cont01701_init","GLOBAL",1)
  ContainerEnable("Con01701",TRUE)	
  //Createcreature("MINSC",[370.2220],10) 
END

//  salle de réunion: Containers 2 découvert
IF
  OpenState("DOOR0002",TRUE)	
  Global("cont01702_init","GLOBAL",0)	
THEN
  RESPONSE #100
  SetGlobal("cont01702_init","GLOBAL",1)
  ContainerEnable("Con01702",TRUE)	
  //Createcreature("MINSC",[370.2220],10)
  //Createcreature("MINSC",[370.2220],10)
END


// Salle sarcophages: Le groupe sort vainqueur des épreuves de Bhaal. Les serviteurs de Bhaal sortent des sarcophages et apparaissent!
IF 
 Global("Bhaal_epreuves","GLOBAL",5)
THEN
 RESPONSE #100
 SetGlobal("Bhaal_epreuves","GLOBAL",6)
 
//Createcreature("MINSC",[710.350],10)  
//Createcreature("MINSC",[710.350],10)  

  // containers activés
 ContainerEnable("Con017S1",TRUE)
 ContainerEnable("Con017s2",TRUE)
 ContainerEnable("Con017s3",TRUE)
 ContainerEnable("Con017s4",TRUE)
 ContainerEnable("Con017s5",TRUE)
 ContainerEnable("Con017s6",TRUE)
 ContainerEnable("Con017s7",TRUE)
 ContainerEnable("Con017s8",TRUE)
 
 // Point info desactivés
 TriggerActivation("Cot017s1",FALSE) 
 TriggerActivation("Cot017s2",FALSE)
 TriggerActivation("Cot017s3",FALSE)
 TriggerActivation("Cot017s4",FALSE)
 TriggerActivation("Cot017s5",FALSE)
 TriggerActivation("Cot017s6",FALSE)
 TriggerActivation("Cot017s7",FALSE)
 TriggerActivation("Cot017s8",FALSE)   
END

// Le groupe prend les restes de Massena dans son équipement: le collier de massena apparait dans l'équipement ***********************************************************
IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER1)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER1,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER2)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER2,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER3)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER3,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER4)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER4,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER5)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER5,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 !Contains("SKELP01","Cont003")
 HasItem("Skelp01",PLAYER6)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER6,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

// Le cadavre n'est plus dans l'équipement du groupe: le collier disparait.
IF
 !PartyHasItem("Skelp01")
 PartyHasItem("AMUP02") 
 Global("collier_massena_init","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",0)
 TakePartyItem("AMUP02")
END

