// 1ière arrivée: la porte se ferme derrière le groupe
IF
 Global("com012_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("com012_init","GLOBAL",1) 
 
 PlaySound("AMB_D04A") 
END

// Livre d'Ekilis en possession du groupe ou révelation d'Ekilis: evolution histoire du temple + trésors de Bhaal ******************************************************************************
IF
 Global("livre_ekilis","GLOBAL",0) 
 PartyHasItemIdentified("BOKP07")
THEN
 RESPONSE #100
 SetGlobal("livre_ekilis","GLOBAL",1)
 SetGlobal("Q_tresor_bhaal","GLOBAL",1) 
  
 // Histoire de Bhaal
 AddJournalEntry(@4,QUEST)   
END

IF
 Global("Q_tresor_bhaal","GLOBAL",1) 
THEN
 RESPONSE #100
 SetGlobal("Q_tresor_bhaal","GLOBAL",2) 

 // Le trésor de Bhaal 
 EraseJournalEntry(@50)
 EraseJournalEntry(@51)
 EraseJournalEntry(@52)
 EraseJournalEntry(@53)
 EraseJournalEntry(@54)
 AddJournalEntry(@55,QUEST_DONE)   
 AddXpObject(PLAYER1,1000)
END


// la porte se ferme **********************************************************************************************************************************************
IF
 OpenState("DOOR0001",FALSE)
 Global("Bruit_fermeture","COM012",0)
THEN
 RESPONSE #100
 SetGlobal("Bruit_fermeture","COM012",1)
 SetGlobal("Bruit_ouverture","COM012",0)
 
 //Createcreature("anomen9",[277.224],10)
 
 
 Wait(2)
 DisplayString(PLAYER1,@2)
 
 // Quête: sortir d'ici
 AddJournalEntry(@1,QUEST)
 
 TriggerActivation("Com027",FALSE)
END

// la porte s'ouvre
IF
 OpenState("DOOR0001",TRUE)
 Global("Bruit_ouverture","COM012",0)
THEN
 RESPONSE #100
 SetGlobal("Bruit_ouverture","COM012",1)
 SetGlobal("Bruit_fermeture","COM012",0)

 //Createcreature("minsc",[277.224],10)
 //PlaySound("AMB_D04A") 
 
 TriggerActivation("Com027",TRUE)
END

// Le crâne de Kept a été placé: la porte s'ouvre
IF
 Global("Crane_place","GLOBAL",1)
 OpenState("DOOR0001",FALSE)
THEN
 RESPONSE #100
 
 PlaySound("AMB_D04A")
 Unlock("DOOR0001")
 OpenDoor("DOOR0001")
END

// Le crâne de Kept a été retiré: la porte se ferme
IF
 Global("Crane_place","GLOBAL",0)
 OpenState("DOOR0001",TRUE)
THEN
 RESPONSE #100
 
 PlaySound("AMB_D04A")
 CloseDoor("DOOR0001")
 lock("DOOR0001") 
END


// Ekilis devient l'allié du groupe: il sera dans chaque carte où le PNJ qu'il suit prend une sortie
IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM012","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM012",PLAYER1)
  Global("ekilis_follow","GLOBAL",1)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER1)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM012","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM012",PLAYER2)
  Global("ekilis_follow","GLOBAL",2)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER2)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM012","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM012",PLAYER3)
  Global("ekilis_follow","GLOBAL",3)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER3)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM012","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM012",PLAYER4)
  Global("ekilis_follow","GLOBAL",4)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER4)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM012","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM012",PLAYER5)
  Global("ekilis_follow","GLOBAL",5)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER5)
  Wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM012","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM012",PLAYER6)
  Global("ekilis_follow","GLOBAL",6)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER6)
  Wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END


// Le groupe prend les restes de Massena dans son équipement (COM013): le collier de massena apparait dans l'équipement ***********************************************************
IF
 HasItem("Skelp01",PLAYER1)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER1,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 HasItem("Skelp01",PLAYER2)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER2,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 HasItem("Skelp01",PLAYER3)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER3,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 HasItem("Skelp01",PLAYER4)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER4,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 HasItem("Skelp01",PLAYER5)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER5,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

IF
 HasItem("Skelp01",PLAYER6)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 ActionOverride(PLAYER6,CreateItem("AMUP02",0,0,0)) 
 AddJournalEntry(@1,QUEST)
END

// Le cadavre n'est plus dans l'équipement du groupe: le collier disparait.
IF
 PartyHasItem("AMUP02") 
 Global("collier_massena_init","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",0)
 TakePartyItem("AMUP02")
END