IF
  OnCreation()
  Global("COM014_INIT","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("COM014_INIT","GLOBAL",1)
    CreateCreature("COEKILIS",[3636.1366],1)
    
    CreateCreature("COMINAU1",[1100.490],10)
    CreateCreature("COMINAU1",[1166.529],10)
    CreateCreature("COMINAU2",[1166.529],10)
    CreateCreature("COMINAU2",[1166.529],10)
    CreateCreature("COMINAU3",[1166.529],10)
    CreateCreature("ELEMEP01",[3200.1070],10)
    CreateCreature("ELEMEP02",[3320.1170],10)
    CreateCreature("ELEMEP03",[3265.1180],10)
    CreateCreature("ELEMEP08",[3600.1000],10)
    CreateCreature("ELEMEP05",[3975.1100],10)    
        
    CreateCreature("BAT_IN",[1260.2035],10)
    CreateCreature("BAT_IN",[1400.2056],10)
    CreateCreature("BAT_IN",[2500.650],10)
    CreateCreature("BAT_IN",[2550.670],10)
    CreateCreature("BAT_IN",[1450.800],10)
    CreateCreature("BAT_IN",[1470.820],10)    
    
    ContainerEnable("CACHE01",FALSE)
    ContainerEnable("CACHE02",FALSE)
    ContainerEnable("CACHE03",FALSE)
END

/*
// attente avant nouvelle TP possible via le collier de Massena
IF
 Global("TimeTP14","GLOBAL",1) 
 GlobalTimerExpired("TIMER_init_TP","GLOBAL")
THEN
 RESPONSE #100
 seTGlobal("TimeTP14","GLOBAL",0)  
 SetGlobal("TimeTP","GLOBAL",0)  
 
 createcreature("COFANT1",[630.520],10) 
END

IF
 Global("TimeTP15","GLOBAL",1) 
 GlobalTimerExpired("TIMER_init_TP","GLOBAL")
THEN
 RESPONSE #100
 sETGlobal("TimeTP15","GLOBAL",0)  
 SetGlobal("TimeTP","GLOBAL",0)  
 
 createcreature("COFANT1",[630.520],10) 
 createcreature("COFANT2",[630.520],10) 
END
*/

// Livre d'Ekilis en possession du groupe ou révelation d'Ekilis: evolution histoire du temple + trésors de Bhaal ******************************************************************************
IF
 Global("livre_ekilis","GLOBAL",0) 
 PartyHasItemIdentified("BOKP07")
THEN
 RESPONSE #100
 SetGlobal("livre_ekilis","GLOBAL",1)
 SetGlobal("Q_tresor_bhaal","GLOBAL",1) 
  
 // Histoire de Bhaal
 AddJournalEntry(@9,QUEST)   
END


IF
 Global("Q_tresor_bhaal","GLOBAL",1)
 Global("ekilis_cmb_direct","GLOBAL",0) 
THEN
 RESPONSE #100
 SetGlobal("Q_tresor_bhaal","GLOBAL",2) 

 // Le trésor de Bhaal 
 EraseJournalEntry(@50)
 EraseJournalEntry(@51)
 EraseJournalEntry(@52)
 EraseJournalEntry(@53)
 EraseJournalEntry(@54)
 AddJournalEntry(@55,QUEST_DONE)   
 AddXpObject(PLAYER1,1000)
END

// Ekilis devient l'allié du groupe: il sera dans chaque carte où le PNJ qu'il suit prend une sortie
IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM014",PLAYER1)
  Global("ekilis_follow","GLOBAL",1)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER1)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM014",PLAYER2)
  Global("ekilis_follow","GLOBAL",2)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER2)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM014",PLAYER3)
  Global("ekilis_follow","GLOBAL",3)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER3)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM014",PLAYER4)
  Global("ekilis_follow","GLOBAL",4)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER4)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM014",PLAYER5)
  Global("ekilis_follow","GLOBAL",5)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER5)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM014",PLAYER6)
  Global("ekilis_follow","GLOBAL",6)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER6)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END



// cache à bijoux d'Ekilis découverte
IF
  OpenState("CACHE",TRUE)		
  Global("CACHE01","COM014",0)
THEN
  RESPONSE #100
  SetGlobal("CACHE01","COM014",1)	
  
  ContainerEnable("Cache01",TRUE)	// container accessible si le PS est découvert
END

// cache à potions/projectiles d'Ekilis découverte
IF
  OpenState("CACHE2",TRUE)		
  Global("CACHE02","COM014",0)
THEN
  RESPONSE #100
  SetGlobal("CACHE02","COM014",1)	
  
  ContainerEnable("Cache02",TRUE)	// container accessible si le PS est découvert
END

// baton de commandement 3: cache découverte
IF
  OpenState("CACHE3",TRUE)		
  Global("BatonC3","COM014",0)
THEN
  RESPONSE #100
  SetGlobal("BatonC3","COM014",1)	
  
  ContainerEnable("Cache03",TRUE)	// container accessible si le PS est découvert 
END

// gestion de la grille en fonction de la position du levier ***************************************************************************************************************
IF
 OpenState("LEVIER01",TRUE)
 Global("levier01","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("levier01","GLOBAL",0)
 
 OpenDoor("HERSE01")
END

IF
 OpenState("LEVIER01",FALSE)
 Global("levier01","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("levier01","GLOBAL",1)
 
 CloseDoor("HERSE01")  
END

// Le groupe prend les restes de Massena dans son équipement: le collier de massena apparait dans l'équipement *************************************************************
IF
 HasItem("Skelp01",PLAYER1)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",1)
 ActionOverride(PLAYER1,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER2)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",2)
 ActionOverride(PLAYER2,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER3)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",3)
 ActionOverride(PLAYER3,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER4)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",4)
 ActionOverride(PLAYER4,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER5)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",5)
 ActionOverride(PLAYER5,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER6)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",6)
 ActionOverride(PLAYER6,CreateItem("AMUP02",0,0,0)) 
END

// Le cadavre de Massena n'est plus dans l'équipement du groupe: le collier disparait. *************************************************************************************
IF
 !PartyHasItem("Skelp01")
 PartyHasItem("AMUP02") 
 Global("collier_massena_init","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",0)
 TakePartyItem("AMUP02")
END



























/*




IF
  OpenState("CACHE",TRUE)
  Global("CACHE01","COM014",0)
THEN
  RESPONSE #100
    SetGlobal("CACHE01","COM014",1)
    ContainerEnable("CACHE01",TRUE)
END

IF
  OpenState("CACHE2",TRUE)
  Global("CACHE02","COM014",0)
THEN
  RESPONSE #100
    SetGlobal("CACHE02","COM014",1)
    ContainerEnable("CACHE02",TRUE)
END

IF
  OpenState("CACHE3",TRUE)
  Global("BATONC3","COM014",0)
THEN
  RESPONSE #100
    SetGlobal("BATONC3","COM014",1)
    ContainerEnable("CACHE03",TRUE)
END

IF
  OpenState("LEVIER01",TRUE)
  Global("LEVIER01","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("LEVIER01","GLOBAL",0)
    OpenDoor("HERSE01")
END

IF
  OpenState("LEVIER01",FALSE)
  Global("LEVIER01","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("LEVIER01","GLOBAL",1)
    CloseDoor("HERSE01")
END


IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM014",PLAYER2)
  Global("ekilis_follow","GLOBAL",2)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER2)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM014",PLAYER3)
  Global("ekilis_follow","GLOBAL",3)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER3)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM014",PLAYER4)
  Global("ekilis_follow","GLOBAL",4)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER4)
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM014",PLAYER5)
  Global("ekilis_follow","GLOBAL",5)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER5)
  Wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1) 
  !AreaCheckObject("COM014","COEKILIS")
  !Dead("COEKILIS")
  AreaCheckObject("COM014",PLAYER6)
  Global("ekilis_follow","GLOBAL",6)
THEN
  RESPONSE #100
  MoveGlobalObject("COEKILIS",PLAYER6)
  Wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END


IF
 Oncreation()
 Global("COM014_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("COM014_init","GLOBAL",1)
 
 // Ekilis endormis via anneau stase
 //Createcreature("COEKILIS",[3600.1366],10)
 Createcreature("COEKILIS",[2930.2530],10)

 // Prison Minautore
 Createcreature("COMINAU1",[1100.490],10)
 Createcreature("COMINAU1",[1166.529],10) 
 createcreature("COMINAU2",[1166.529],10) 
 Createcreature("COMINAU2",[1166.529],10) 
 Createcreature("COMINAU3",[1166.529],10) 
 
 // Caisses méphites
 Createcreature("ELEMEP01",[3200.1070],10)
 Createcreature("ELEMEP02",[3320.1170],10)
 Createcreature("ELEMEP03",[3265.1180],10)
 Createcreature("ELEMEP04",[3600.1000],10)
 Createcreature("ELEMEP05",[3975.1100],10)  
 
 // Caches d'Ekilis
 ContainerEnable("Cache01",FALSE)	 // Cache à trésors Ekilis
 ContainerEnable("Cache02",FALSE)	 // Cache à potions Ekilis
 ContainerEnable("Cache03",FALSE)	 // Cache baton de commandement
END

// Gestion de l'accès à la cache au potion d'Ekilis
IF
  OnCreation()				// La première fois que l'on entre dans la carte.
  Global("CACHE02","COM014",0)
THEN
  RESPONSE #100
  SetGlobal("CACHE02","COM014",1)	
  ContainerEnable("CACHE02",FALSE)	
  Continue()
END

IF
  OpenState("CACHE02",TRUE)		
  Global("CACHE02B","COM014",0)
THEN
  RESPONSE #100
  SetGlobal("CACHE02B","COM014",1)	
  ContainerEnable("CACHE02",TRUE)	// container accessible si le PS est découvert
END

IF
 Oncreation()
THEN
 RESPONSE #100
 
 // Ekilis endormis
 Createcreature("COEKILIS",[3600.1366],10)
END

 // Animation sphère de magie
IF
 Global("STASE_EKILIS","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("STASE_EKILIS","GLOBAL",1)
 
 actionoverride("COEKILIS",ReallyForceSpell("COEKILIS",CLERIC_SANCTUARY))
 wait(10)  
END

// Stase en continue
IF
 Global("STASE_EKILIS","GLOBAL",1)
 !StateCheck("COEKILIS",CLERIC_SANCTUARY)
THEN
 RESPONSE #100
 SetGlobal("STASE_EKILIS","GLOBAL",0)
END

// TEST container
IF 
 Opened("Chest04")
THEN
 RESPONSE #100
 //Createcreature("MINSC",[3800.1170],10)
END


*/