IF
 Oncreation()
 Global("COM015_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("COM015_init","GLOBAL",1)
  
  //GRILLE FERMEE
  CloseDoor("DOOR0002") 
  CloseDoor("DOOR0003") 
  
  // PS sarcophage non trouvé
  TriggerActivation("DOOR016",FALSE)
      
  // Gestion des wyvernes
  Createcreature("WYVERN",[510.950],10) 
  GiveItem("MISC52","WYVERN")
  Createcreature("WYVERBA",[510.950],10)     
  Createcreature("WYVERBA",[510.950],10)  
  
  // Positionnement des prisonniers dans les cellules
  Createcreature("TROLL01",[3900.1690],10)     
  Createcreature("TROLL01",[3900.1690],10)  
  Createcreature("COUMBER",[2880.2115],10)     
  Createcreature("COUMBER",[2880.2115],10)    
  
  // positionnement de Massena
  Createcreature("COMASSE1",[1990.790],6) 
  SmallWait(10)
  ActionOverride("COMASSE1",SetDialogue("COMASSE2"))
  SmallWait(10)
  DeActivate("COMASSE1")    
  
  // Cache Batons de commandements
  ContainerEnable("Container019",FALSE)	
  ContainerEnable("Container020",FALSE)
    
  // Ajout des chauves-souris
  CreateCreature("COBAT2",[2770.1360],0)
  CreateCreature("COBAT2",[2920.1770],0)
  CreateCreature("COBAT2",[3350.1640],0)
  CreateCreature("COBAT2",[3530.1900],0)
  CreateCreature("COBAT2",[4070.1870],0)  
  CreateCreature("COBAT2",[4140.1970],0)
  CreateCreature("COBAT2",[3240.2040],0) 
  CreateCreature("COBAT2",[2450.2300],0) 
  CreateCreature("COBAT2",[2770.1360],0)
  CreateCreature("COBAT2",[2920.1770],0)
  CreateCreature("COBAT2",[3350.1640],0)
  CreateCreature("COBAT2",[3530.1900],0)
  CreateCreature("COBAT2",[4070.1870],0)  
  CreateCreature("COBAT2",[4140.1970],0)
  CreateCreature("COBAT2",[3240.2040],0) 
  CreateCreature("COBAT2",[2450.2300],0) 
END


IF
  Disarmed("COT01515")
THEN
  RESPONSE #100
    //PlaySound("COBOO1")
	wait(2)
	//PlaySound("COBOO1")
    TriggerActivation("COT01515",FALSE)
END


// Ekilis alerte le groupe que le coffre est piègé. *********************************************************************************
IF
  Global("ekilis_alliance","GLOBAL",1)
  AreaCheckObject("COM015","COEKILIS")
  !Dead("COEKILIS")  
  Global("ekilis_coffre_piege","COM015",0)
THEN 
 RESPONSE #100
 SetGlobal("ekilis_coffre_piege","COM015",1)
 Wait(2)
 DisplayStringHead("COEKILIS",@9) // ~Attention, le coffre est à éviter. Il est piègé.~
END


// Livre d'Ekilis en possession du groupe ou révelation d'Ekilis: evolution histoire du temple + trésors de Bhaal ******************************************************************************
IF
 Global("livre_ekilis","GLOBAL",0) 
 PartyHasItemIdentified("BOKP07")
THEN
 RESPONSE #100
 SetGlobal("livre_ekilis","GLOBAL",1)
 SetGlobal("Q_tresor_bhaal","GLOBAL",1) 
  
 // Histoire de Bhaal
 AddJournalEntry(@70,QUEST)   
END

IF
 Global("Q_tresor_bhaal","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("Q_tresor_bhaal","GLOBAL",2) 

 // Le trésor de Bhaal 
 EraseJournalEntry(@50)
 EraseJournalEntry(@51)
 EraseJournalEntry(@52)
 EraseJournalEntry(@53)
 EraseJournalEntry(@54)
 AddJournalEntry(@55,QUEST_DONE)   
 AddXpObject(PLAYER1,1000)
END

// Le groupe prend les restes de Massena dans son équipement: le collier de massena apparait dans l'équipement *************************************************************
IF
 HasItem("Skelp01",PLAYER1)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",1)
 ActionOverride(PLAYER1,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER2)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",2)
 ActionOverride(PLAYER2,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER3)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",3)
 ActionOverride(PLAYER3,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER4)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",4)
 ActionOverride(PLAYER4,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER5)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",5)
 ActionOverride(PLAYER5,CreateItem("AMUP02",0,0,0)) 
END

IF
 HasItem("Skelp01",PLAYER6)
 Global("collier_massena_init","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",1)
 SetGlobal("collier_TP_PLAYER","GLOBAL",6)
 ActionOverride(PLAYER6,CreateItem("AMUP02",0,0,0)) 
END

// Le cadavre de Massena n'est plus dans l'équipement du groupe: le collier disparait. *************************************************************************************
IF
 !PartyHasItem("Skelp01")
 PartyHasItem("AMUP02") 
 Global("collier_massena_init","GLOBAL",1)
THEN
 RESPONSE #100
 SetGlobal("collier_massena_init","GLOBAL",0)
 TakePartyItem("AMUP02")
END


// attente avant nouvelle TP possible avant le collier de Massena **************************************************************************************************************************
IF
 Global("TimeTP14","GLOBAL",1)
 GlobalTimerExpired("TIMER_init_TP","GLOBAL") 
THEN
 RESPONSE #100
 sETGlobal("TimeTP14","GLOBAL",0)  
 SetGlobal("TimeTP","GLOBAL",0)  
END

IF
 Global("TimeTP15","GLOBAL",1) 
 GlobalTimerExpired("TIMER_init_TP","GLOBAL")
THEN
 RESPONSE #100
 sETGlobal("TimeTP15","GLOBAL",0)  
 SetGlobal("TimeTP","GLOBAL",0)  
END

// Ekilis devient l'allié du groupe: il sera dans chaque carte où le PNJ qu'il suit prend une sortie **************************************************************************************************************************
IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM015","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM015",PLAYER1)
  Global("ekilis_follow","GLOBAL",1)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  //Createcreature("MINSC",[870.1370],10)  
  MoveGlobalObject("COEKILIS",PLAYER1)

  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM015","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM015",PLAYER2)
  Global("ekilis_follow","GLOBAL",2)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  //Createcreature("MINSC",[870.1370],10)  
  MoveGlobalObject("COEKILIS",PLAYER2)

  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM015","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM015",PLAYER3)
  Global("ekilis_follow","GLOBAL",3)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  //Createcreature("MINSC",[870.1370],10)  
  MoveGlobalObject("COEKILIS",PLAYER3)
  
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM015","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM015",PLAYER4)
  Global("ekilis_follow","GLOBAL",4)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  //Createcreature("MINSC",[870.1370],10)  
  MoveGlobalObject("COEKILIS",PLAYER4)

  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM015","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM015",PLAYER5)
  Global("ekilis_follow","GLOBAL",5)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  //Createcreature("MINSC",[870.1370],10)  
  MoveGlobalObject("COEKILIS",PLAYER5)

  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END

IF
  Global("ekilis_alliance","GLOBAL",1)
  !AreaCheckObject("COM015","COEKILIS")
  !Dead("COEKILIS")  
  AreaCheckObject("COM015",PLAYER6)
  Global("ekilis_follow","GLOBAL",6)
  Global("TimeTP","GLOBAL",0)
THEN
  RESPONSE #100
  //Createcreature("MINSC",[870.1370],10)  
  MoveGlobalObject("COEKILIS",PLAYER6)
  
  wait(2)
  SetGlobal("ekilis_follow","GLOBAL",0)
END



// DLG Massena terminé ***************************************************************************************************************************************************************************************
IF
 Global("ekilis_deactivate","Global",1)
THEN
 RESPONSE #100
 SetGlobal("ekilis_deactivate","Global",0)
 
 Wait(2)
 Deactivate("COMASSE1")
END

IF
 Global("fin_dial_massena","Global",0)
 Global("Massena_sarcophage","Global",1)
THEN
 RESPONSE #100
 SetGlobal("fin_dial_massena","Global",1)
 
 Deactivate("COMASSE1")
END


// Tantqu'il manque des pierres dans le coffre, les créatures apparaissent et s'attaquent au propriétaire. *************************************************************
IF
 GlobalLT("recup_pierre_feu","GLOBAL",3)
 !Contains("MISC16","Con01513")
 Global("recup_pierre_top_feu","GLOBAL",0) 
THEN
 RESPONSE #100
 IncrementGlobal("recup_pierre_feu","GLOBAL",1)
 SetGlobal("recup_pierre_top_feu","GLOBAL",1) 
 CreateCreature("GIBBER_F",[828.1300],10)
 
 RESPONSE #100
 IncrementGlobal("recup_pierre_feu","GLOBAL",1)
 SetGlobal("recup_pierre_top_feu","GLOBAL",1) 
 CreateCreature("GIBBER_F",[903.1372],10)
END

IF
 GlobalLT("recup_pierre_froid","GLOBAL",3)
 !Contains("MISC39","Con01513")
 Global("recup_pierre_top_froid","GLOBAL",0) 
THEN
 RESPONSE #100
 IncrementGlobal("recup_pierre_froid","GLOBAL",1)
 SetGlobal("recup_pierre_top_froid","GLOBAL",1) 
 CreateCreature("GIBBER_G",[912.1300],10)
 
 RESPONSE #100
 IncrementGlobal("recup_pierre_froid","GLOBAL",1)
 SetGlobal("recup_pierre_top_froid","GLOBAL",1) 
 CreateCreature("GIBBER_G",[933.1943],10)
END

IF
 GlobalLT("recup_pierre_acide","GLOBAL",3)
 !Contains("MISC30","Con01513")
 Global("recup_pierre_top_acide","GLOBAL",0) 
THEN
 RESPONSE #100
 IncrementGlobal("recup_pierre_acide","GLOBAL",1)
 SetGlobal("recup_pierre_top_acide","GLOBAL",1) 
 CreateCreature("GIBBER_A",[809.1337],10) 
 
 RESPONSE #100
 IncrementGlobal("recup_pierre_acide","GLOBAL",1)
 SetGlobal("recup_pierre_top_acide","GLOBAL",1) 
 CreateCreature("GIBBER_A",[828.1300],10) 
END

IF
 GlobalLT("recup_pierre_elec","GLOBAL",3)
 !Contains("MISC41","Con01513")
 Global("recup_pierre_top_elec","GLOBAL",0) 
THEN
 RESPONSE #100
 IncrementGlobal("recup_pierre_elec","GLOBAL",1)
 SetGlobal("recup_pierre_top_elec","GLOBAL",1)
 CreateCreature("GIBBER_E",[912.1300],10) 
 
 RESPONSE #100
 IncrementGlobal("recup_pierre_elec","GLOBAL",1)
 SetGlobal("recup_pierre_top_elec","GLOBAL",1)
 CreateCreature("GIBBER_E",[933.1343],10) 
END

IF
 GlobalLT("recup_pierre_poison","GLOBAL",3)
 !Contains("MISC43","Con01513")
 Global("recup_pierre_top_poison","GLOBAL",0) 
THEN
 RESPONSE #100
 IncrementGlobal("recup_pierre_poison","GLOBAL",1)
 SetGlobal("recup_pierre_top_poison","GLOBAL",1) 
 CreateCreature("GIBBER_P",[809.1337],10)
 
 RESPONSE #100
 IncrementGlobal("recup_pierre_poison","GLOBAL",1)
 SetGlobal("recup_pierre_top_poison","GLOBAL",1) 
 CreateCreature("GIBBER_P",[903.1372],10)
END


// nouvelle vague
IF
 DELAY(10)
  OR(5)
   Global("recup_pierre_top_poison","GLOBAL",1) 
   Global("recup_pierre_top_froid","GLOBAL",1) 
   Global("recup_pierre_top_poison","GLOBAL",1) 
   Global("recup_pierre_top_acide","GLOBAL",1) 
   Global("recup_pierre_top_elec","GLOBAL",1)    
THEN
 RESPONSE #100
 SetGlobal("recup_pierre_top_poison","GLOBAL",0) 
 SetGlobal("recup_pierre_top_froid","GLOBAL",0) 
 SetGlobal("recup_pierre_top_poison","GLOBAL",0) 
 SetGlobal("recup_pierre_top_acide","GLOBAL",0) 
 SetGlobal("recup_pierre_top_elec","GLOBAL",0)  
END

// Mort de la grande Wyvern: sa tête est à placer dans la cache pour ouvrir le PS **************************************************************************************************************************
IF
 HasItem("MISC52","Container018")
 HasItem("MISC52","Container017")
 OpenState("DOOR0001",FALSE)
THEN
  RESPONSE #100  
  OpenDoor("DOOR0001")
  SetGlobal("COT01501","COM015",3)
  PlaySound("EFF_M15")
END

/*
// Grande grille ouverte: bruit grille
IF 
 OpenState("DOOR0001",TRUE)
THEN
 RESPONSE #100
 Playsound("AMB_D01A")
END
*/

// La porte a été fermée. Au bou d'un certain temps le PS s'ouvre à nouveau **************************************************************************************************************************
IF
  GlobalTimerExpired("Com015_PS_ferme","COM015")
  Global("COT01501","COM015",2) 
THEN
  RESPONSE #100
  SetGlobal("COT01501","COM015",3)
  PlaySound("EFF_M15")
END

// baton de commandement 1: cache découverte **************************************************************************************************************************
IF
  OpenState("DOOR0008",TRUE)		
  Global("BatonC1","COM015",0)
THEN
  RESPONSE #100
  SetGlobal("BatonC1","COM015",1)	
  ContainerEnable("Container019",TRUE)	// container accessible si le PS est découvert
END

// baton de commandement 2: cache découverte **************************************************************************************************************************
IF
  OpenState("DOOR0009",TRUE)		
  Global("BatonC2","COM015",0)
THEN
  RESPONSE #100
  SetGlobal("BatonC2","COM015",1)	
  ContainerEnable("Container020",TRUE)	// container accessible si le PS est découvert
END

// gestion de la grille en fonction de la position de l'actionneur **************************************************************************************************************************
IF
  OpenState("DOOR0003",TRUE)
  OpenState("DOOR0002",FALSE)
THEN
 RESPONSE #100 
 OpenDoor("DOOR0002")
 Playsound("AMB_D01A")
 SetGlobal("COM015_grille","GLOBAL",1)
END

IF
  OpenState("DOOR0003",FALSE)
  OpenState("DOOR0002",TRUE)
THEN
 RESPONSE #100 
 CloseDoor("DOOR0002") 
 Playsound("AMB_D01A")
 SetGlobal("COM015_grille","GLOBAL",0) 
END

// Gestion du PS sarcophage **************************************************************************************************************************
IF
  OpenState("DOOR0004",TRUE)    
THEN
 RESPONSE #100 
 TriggerActivation("DOOR016",TRUE) 
END

IF
  OpenState("DOOR0004",FALSE)  
THEN
 RESPONSE #100 
 TriggerActivation("DOOR016",FALSE)  
END


