IF
 Clicked([ANYONE])
 !Range(lasttrigger,7)
THEN
 RESPONSE #100
 ActionOverride(lasttrigger,MoveToObject("Cot022b9"))
END

IF
 Clicked([ANYONE])
 Range(lasttrigger,7)
 Global("bassin9_click","COM022",0)
THEN
 RESPONSE #100
 SetGlobal("bassin9_click","COM022",1)
 DisplayStringHead(LastTrigger,@13)
END

IF
 Clicked([ANYONE])
 Range(lasttrigger,7)
 Global("bassin9_click","COM022",1)
THEN
 RESPONSE #100
 DisplayStringHead(LastTrigger,@14)
END