IF
 Clicked([ANYONE])
 Global("bassin5_click","COM022",0)
 !Range(lasttrigger,7)
THEN
 RESPONSE #100
 ActionOverride(lasttrigger,MoveToObject("Cot022b5"))
END

IF
 Clicked([ANYONE])
 Global("bassin5_click","COM022",0)
 !HasItem("MISCP55",LastTrigger)
 Range(lasttrigger,7)
THEN
 RESPONSE #100
 //SetGlobal("bassin5_click","COM022",1)
 // ~Sous le bassin vous distinguez une vanne. La tourner devrait vider le bassin mais vous n'avez pas d'outil.~
 DisplayStringHead(LastTrigger,@1)
END

IF
 Clicked([ANYONE])
 Global("bassin5_click","COM022",0)
 HasItem("MISCP55",LastTrigger)
 Range(lasttrigger,7)
THEN
 RESPONSE #100
 SetGlobal("bassin5_click","COM022",1)
 // ~Sous le bassin vous distinguez une vanne. Avec l'outil, la tourner devrait vider le bassin.~
 DisplayStringHead(LastTrigger,@2)
END

IF
 Clicked([ANYONE])
 Global("bassin5_click","COM022",1)
 HasItem("MISCP55",LastTrigger)
 CheckStatLT(LastTrigger,11,STR)
 Range(lasttrigger,7)
THEN
 RESPONSE #100
 //~Vous utilisez l'outil pour fermer la vanne mais elle résiste, vous manquez de force.~
 DisplayStringHead(LastTrigger,@3)
END

IF
 Clicked([ANYONE])
 Global("bassin5_click","COM022",1)
 HasItem("MISCP55",LastTrigger)
 CheckStatGT(LastTrigger,11,STR)
 Range(lasttrigger,7)
THEN
 RESPONSE #100
 SetGlobal("bassin5_click","COM022",2)
 
 // ~Vous bandez vos muscles et parvenez à ouvrir la vanne avec l'outil. Le bassin se vide.~
 DisplayStringHead(LastTrigger,@4)
 
 // image Bassin vidé
 CloseDoor("Bassg5")

 SoundActivate("COM022B5",FALSE)
 TriggerActivation("Cot022b5",FALSE)
END
