// Déclenche l'apparition d'une créature
IF
IsOverMe([PC])
 GlobalTimerExpired("com022_bassin1","COM022")
THEN
 RESPONSE #100
 SetGlobalTimer("com022_bassin1","COM022",10)
 Createcreature("DJINNISU",[-1.-1],10)
 PlaySound("EFF_E04")
 CreateVisualEffectObject("gwshair2","DJINNISU")
 
 RESPONSE #100
 SetGlobalTimer("com022_bassin1","COM022",10)
 Createcreature("VAMPFMF01",[-1.-1],10)
 PlaySound("EFF_E04")
 CreateVisualEffectObject("gwshair2","VAMPFMF01")
 
 RESPONSE #100
 SetGlobalTimer("com022_bassin1","COM022",10)
 Createcreature("TROLL01",[-1.-1],10)
 PlaySound("EFF_E04")
 CreateVisualEffectObject("gwshair2","TROLL01")
 
 RESPONSE #100
 SetGlobalTimer("com022_bassin1","COM022",10)
 Createcreature("WEREWO",[-1.-1],10)  
 PlaySound("EFF_E04")
 CreateVisualEffectObject("gwshair2","WEREWO")
END