// au 1ier passage du Charname le TS se déclenche.
IF
 Clicked([0])
 Range(PLAYER1,6)
 Global("COM022_TS","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("COM022_TS","GLOBAL",1) // Fin TS
 SetGlobal("COM022_grille","GLOBAL",1)
 
 //PlaySound("COBOO1") // Temoin
 
 TextScreen("COTS008")
 ActionOverride(PLAYER1,LeaveAreaLUA("COM022","",[2515.585],5)) 
 Continue()
END

IF
 Clicked([0])
 Range(PLAYER2,6)
THEN
 RESPONSE #100
 SetGlobal("COM022_grille","GLOBAL",1)
 Wait(1) 
 
 ActionOverride(PLAYER2,LeaveAreaLUA("COM022","",[2515.585],5)) 
 Continue()
END

IF
 Clicked([0])
 Range(PLAYER3,6)
THEN
 RESPONSE #100
 SetGlobal("COM022_grille","GLOBAL",1)
 Wait(1)
  
 ActionOverride(PLAYER3,LeaveAreaLUA("COM022","",[2515.585],5)) 
 Continue()
END

IF
 Clicked([0])
 Range(PLAYER4,6)
THEN
 RESPONSE #100
 SetGlobal("COM022_grille","GLOBAL",1)
 Wait(1) 
 
 ActionOverride(PLAYER4,LeaveAreaLUA("COM022","",[2515.585],5)) 
 Continue()
END

IF
 Clicked([0])
 Range(PLAYER5,6)
THEN
 RESPONSE #100
 SetGlobal("COM022_grille","GLOBAL",1)
 Wait(1)
   
 ActionOverride(PLAYER5,LeaveAreaLUA("COM022","",[2515.585],5)) 
 Continue()
END

IF
 Clicked([0])
 Range(PLAYER6,6)
THEN
 RESPONSE #100
 SetGlobal("COM022_grille","GLOBAL",1)
 Wait(1)
  
 ActionOverride(PLAYER6,LeaveAreaLUA("COM022","",[2515.585],5)) 
 Continue()
END

