// Déclenchement de l'embuscade
IF
 Entered([PC])
 Global("COM020_embuscade_Zone","COM020",0)
THEN
 // Type araignée ****
 RESPONSE #50
 SetGlobal("COM020_embuscade_Zone","COM020",1)

 // suivi du groupe par la chauve souris espion
 Createcreature("COBATIN",[795.445],10)
 
 Createcreature("SPIDGI",[795.445],10) 
 CreateVisualEffectObject("gwshair7","SPIDGI")
 //ForceSpell("SPIDGI",GREY_MUSHROOM)
 PlaySound("EFF_M03")
 
 Createcreature("SPIDPH",[1007.420],10)
 //ForceSpell("SPIDPH",GREY_MUSHROOM) 
 CreateVisualEffectObject("gwshair7","SPIDPH")
 
 Createcreature("SPIDSw",[823.632],10)
 //ForceSpell("SPIDSw",GREY_MUSHROOM)
 CreateVisualEffectObject("gwshair7","SPIDSw")
 

 // Piège toile d'araignée
 ForceSpellPoint([912.526],"WIZARD_WEB")
  

 // type Fouisseurs ****
 RESPONSE #50
 SetGlobal("COM020_embuscade_Zone","COM020",1)

 // suivi du groupe par la chauve souris espion
 Createcreature("COBATIN",[795.445],10)
 
 PlaySound("EFF_M03")  
 Createcreature("ANKHEG",[795.445],10)
 Createcreature("ANKHEG",[1007.420],10) 
 Createcreature("ANKHEG",[823.632],10) 


 // Type Ver ***
 RESPONSE #50
 SetGlobal("COM020_embuscade_Zone","COM020",1)

 // suivi du groupe par la chauve souris espion
 Createcreature("COBATIN",[795.445],10)
 
 Createcreature("CARRIO",[795.445],10) 
 PlaySound("EFF_M03")
 //ForceSpell("CARRIO",GREY_MUSHROOM)
 CreateVisualEffectObject("gwshair7","CARRIO")
 
 Createcreature("CARRIO",[1007.420],10)
 //ForceSpell("CARRIO",GREY_MUSHROOM)
 CreateVisualEffectObject("gwshair7","CARRIO")
 
 Createcreature("CARRIO",[823.632],10) 
 CreateVisualEffectObject("gwshair7","CARRIO")
 
 Createcreature("CARRIO",[1077.565],10) 
 CreateVisualEffectObject("gwshair7","CARRIO")
END