// personne sur la zone: la porte doit être fermée
IF
 !Range([0],2)
THEN
 RESPONSE #100  
 SetGlobal("Action1_PS5","COM021",0)
END

// un PLAYER ou une créature sur la zone: la porte doit être ouverte
IF
 Range([0],2)
THEN
 RESPONSE #100  
 SetGlobal("Action1_PS5","COM021",1)
END







/*
// si une creature est dans la zone: le PS doit être ouvert
IF
 Entered([0])
 OpenState("PS5",FALSE)
THEN
 RESPONSE #100  
 PlaySound("GAM_21")
 smallWait(50)
 OpenDoor("PS5")
 PlaySound("AMB_D04A")
END

*/