/*
// Le coffre a été ouvert: Maladie apparait si elle n'est pas apparue ***********************************************************************************************
IF
 Global("coffre_ouvert","COM023",1)
 Global("Maladie_apparait","COM023",0)
THEN
 RESPONSE #100
 SetGlobal("coffre_ouvert","COM023",2)
 SetGlobal("Maladie_apparait","COM023",1)
 
 //CreateCreature("MINSC",[1200.600],6) 
 //CreateCreature("MINSC",[1200.600],6) 
 //CreateCreature("MINSC",[1200.600],6) 
 //CreateCreature("MINSC",[1200.600],6)
 
 // Le Sphinx se réveille et parle au groupe
 SetGlobal("Sphinx_destroy","COM023",0)
 OpenDoor("SPHOFF")
 Wait(2)
 CreateCreature("COSPHIN",[882.351],10) // statue pour lancer le sort 
 StartDialogueNoSet([PC])
 Wait(2)
 
 // Lancement sort d'apparition de maladie
 Createcreature("COSPHI1",[1409.724],10) // statue pour recevoir le sort
 SetGlobalTimer("TIME_MALADIE_RECHERCHE","COM023",2)
 SetGlobalTimer("maladie_SPELL","GLOBAL",2)
 ForceSpellRES("COMALAV","COSPHI1")

 // Le Sphinx s'endort
 Wait(1)
 SetGlobal("Sphinx_destroy","COM023",1) 
END
*/