/*
// inutile car script creature)
// L'effigie Caris engage la conversation
IF
 Entered([PC])
 Range([PC],15)
 OR(5)
  Global("Caris_init","COM021",0)
  Global("salle_feu","COM021",1)
  Global("salle_glace","COM021",1)
  GlobalGT("nb_coffre_ouvert","COM021",0)
  OpenState("PS2",TRUE)
THEN
 Response #100
 CreateCreature("COCARIS",[1260.105],6)  
 ActionOverride("COCARIS",StartDialogueNoSet([PC])
END
*/
