// le PS doit être ouvert si au moins un actionneur actif
IF
 OpenState("PS5",FALSE)
 GlobalTimerExpired("PS5_OUVERT","COM021")
 OR(2) 
  Global("Action1_PS5","COM021",1)
  Global("Action2_PS5","COM021",1)
THEN
 RESPONSE #100  

 PlaySound("GAM_21")
 
 OpenDoor("PS5")
 PlaySound("AMB_D04A")
   
 // Relance vérification 
 SetGlobalTimer("PS5_OUVERT","COM021",2) 
END

// le PS reste ouvert si au moins un actionneur actif
IF
 OpenState("PS5",TRUE)
 GlobalTimerExpired("PS5_OUVERT","COM021")
 OR(2) 
  Global("Action1_PS5","COM021",1)
  Global("Action2_PS5","COM021",1)
THEN
 RESPONSE #100  

 PlaySound("GAM_21")
 
 // Relance vérification 
 SetGlobalTimer("PS5_OUVERT","COM021",2) 
END

// le PS est fermé si aucun actionneur actif
IF
  OpenState("PS5",TRUE)
  GlobalTimerExpired("PS5_OUVERT","COM021")
  Global("Action1_PS5","COM021",0)
  Global("Action2_PS5","COM021",0)
THEN
 RESPONSE #100  

 CloseDoor("PS5")
 PlaySound("AMB_D04A")
   
 // Relance vérification 
 SetGlobalTimer("PS5_OUVERT","COM021",2) 
END




/*
// si une creature est dans la zone: le PS doit être ouvert
IF
 GlobalTimerExpired("PS5_OUVERT","COM021")
 OpenState("PS5",FALSE)
 //IsOverme([PC])
 Range([0],2)
THEN
 RESPONSE #100  
 PlaySound("GAM_21")
 
 OpenDoor("PS5")
 PlaySound("AMB_D04A")
   
 // Relance vérification 
 SetGlobalTimer("PS5_OUVERT","COM021",2) 
END

// si une creature est dans la zone: le PS maintenu ouvert
IF
 GlobalTimerExpired("PS5_OUVERT","COM021")
 OpenState("PS5",TRUE)
 //IsOverme([PC])
 Range([0],2)
THEN
 RESPONSE #100 
 PlaySound("GAM_21")
 
 // Relance vérification 
 SetGlobalTimer("PS5_OUVERT","COM021",2) 
END

// si il n'y a pas de creature dans la zone: le PS est fermé
IF
 GlobalTimerExpired("PS5_OUVERT","COM021")
 OpenState("PS5",TRUE)
 !Range([0],2) 
THEN
 RESPONSE #100  
 //SetGlobal("PS5_ferme","COM021",1) 

 CloseDoor("PS5")
 PlaySound("AMB_D04A")
   
 // Relance vérification 
 SetGlobalTimer("PS5_OUVERT","COM021",2) 
END
*/



/* ok
// ouverture du PS5 si qqu'un dessus
IF
 GlobalTimerExpired("PS5_OUVERT","COM021")
 OpenState("PS5",FALSE)
 //IsOverme([PC])
 Range([0],5)
THEN
 RESPONSE #50  
 PlaySound("GAM_21")
 
 Wait(1)
 OpenDoor("PS5")
 PlaySound("AMB_D04A")
   
 // Relance vérification 
 SetGlobalTimer("PS5_OUVERT","COM021",2) 
END

// PS maintenu ouvert
IF
 GlobalTimerExpired("PS5_OUVERT","COM021")
 OpenState("PS5",TRUE)
 //IsOverme([PC])
 Range([0],5)
THEN
 RESPONSE #50  
 PlaySound("GAM_21")
 
 // Relance vérification 
 SetGlobalTimer("PS5_OUVERT","COM021",2) 
END

// PS fermé
IF
 GlobalTimerExpired("PS5_OUVERT","COM021")
 OpenState("PS5",TRUE)
 !Range([0],5)
 
 //Global("PS_OUVERT","COM021",0)
THEN
 RESPONSE #50  
 CloseDoor("PS5")
  
 PlaySound("AMB_D04A")
   
 // Relance vérification 
 SetGlobalTimer("PS5_OUVERT","COM021",2) 
END
*/






/*
IF
  //Range([ANYTHING],3)
  IsOverMe([ANYTHING])
  Global("PS_OUVERT","COM021",0)
  OpenState("PS5",FALSE)
THEN
  RESPONSE #100
  SetGlobal("PS_OUVERT","COM021",1)
  OpenDoor("PS5")
  
END

IF
  //!Range([ANYTHING],3)
  !IsOverMe([ANYTHING])
  Global("PS_OUVERT","COM021",1)
THEN
  RESPONSE #100
  SetGlobal("PS_OUVERT","COM021",0)
END
*/