// La fontaine soigne Kael à distance
IF 
  Global("KAEL_blesse","COM022",1) 
  !Dead("COKAEL")
THEN
 RESPONSE #100 
 SetGlobal("KAEL_blesse","COM022",0) 
 
 TriggerActivation("COT022F",FALSE) 
 ForceSpellRes("COCUREF1","COKAEL") 
 DisplayStringHead("COKAEL",@50)  
 
 RESPONSE #100 
 SetGlobal("KAEL_blesse","COM022",0) 
 
 TriggerActivation("COT022F",FALSE) 
 ForceSpellRes("COCUREF1","COKAEL") 
 DisplayStringHead("COKAEL",@51)  
 
 RESPONSE #100 
 SetGlobal("KAEL_blesse","COM022",0) 
 
 TriggerActivation("COT022F",FALSE) 
 ForceSpellRes("COCUREF1","COKAEL") 
 DisplayStringHead("COKAEL",@52)   

END

/*
// La fontaine soigne Kael
IF 
 IsOverMe("COKAEL")
 HpPercentLT("COKAEL",50)  
THEN
 RESPONSE #100
 ForceSpell("COKAEL",CLERIC_CURE_SERIOUS_WOUNDS)
 Wait(2) 
 DisplayStringHead("COKAEL",@6)
END
*/
