// Déclenchement de l'embuscade
IF
 Entered([PC])
 Global("COM020_embuscade_Zone","COM020",0)
THEN
 // Type araignée ****
 RESPONSE #50
 SetGlobal("COM020_embuscade_Zone","COM020",1)
 
  // suivi du groupe par la chauve souris espion
 Createcreature("COBATIN",[230.380],10)
 PlaySound("EFF_M03")
 
 Createcreature("SPIDGI",[230.380],10) 
 CreateVisualEffectObject("gwshair7","SPIDGI")
 
 Createcreature("SPIDPH",[465.410],10) 
 CreateVisualEffectObject("gwshair7","SPIDPH")
  
 Createcreature("SPIDSw",[480.560],10) 
 CreateVisualEffectObject("gwshair7","SPIDSw")


 // Piège toile d'araignée
 ForceSpellPoint([410.455],"WIZARD_WEB")  
  
 // type Fouisseurs ****
 RESPONSE #50
 SetGlobal("COM020_embuscade_Zone","COM020",1)

 // suivi du groupe par la chauve souris espion
 Createcreature("COBATIN",[230.380],10)
 PlaySound("EFF_M03") 
 
 Createcreature("ANKHEG",[230.380],10)  
 Createcreature("ANKHEG",[465.410],10) 
 Createcreature("ANKHEG",[480.560],10) 
 
 // Lenteur
 ForceSpellPoint([410.455],"WIZARD_SLOW")
 
 // Type Ver ****
 RESPONSE #50
 SetGlobal("COM020_embuscade_Zone","COM020",1)

 // suivi du groupe par la chauve souris espion
 Createcreature("COBATIN",[230.380],10)
 PlaySound("EFF_M03") 
 
 Createcreature("CARRIO",[230.380],10) 
 CreateVisualEffectObject("gwshair7","CARRIO")
 
 Createcreature("CARRIO",[465.410],10) 
 CreateVisualEffectObject("gwshair7","CARRIO")
 
 Createcreature("CARRIO",[480.560],10) 
 CreateVisualEffectObject("gwshair7","CARRIO")
 
 Createcreature("CARRIO",[320.535],10) 
 CreateVisualEffectObject("gwshair7","CARRIO")
END