// si une creature est dans la zone: le PS doit être ouvert
IF
 GlobalTimerExpired("PS4_OUVERT","COM021")
 OpenState("PS4",FALSE)
 //IsOverme([PC])
 Range([0],5)
THEN
 RESPONSE #100 
 PlaySound("GAM_21")
 
 //Wait(1)
 OpenDoor("PS4")
 PlaySound("AMB_D04A")
   
 // Relance vérification 
 SetGlobalTimer("PS4_OUVERT","COM021",2) 
END


// si une creature est dans la zone: le PS maintenu ouvert
IF
 GlobalTimerExpired("PS4_OUVERT","COM021")
 OpenState("PS4",TRUE)
 //IsOverme([PC])
 Range([0],5)
THEN
 RESPONSE #100
 PlaySound("GAM_21")
 
 // Relance vérification 
 SetGlobalTimer("PS4_OUVERT","COM021",2) 
END

// si il n'y a pas de creature dans la zone: le PS est fermé
IF
 GlobalTimerExpired("PS4_OUVERT","COM021")
 OpenState("PS4",TRUE)
 !Range([0],5) 
THEN
 RESPONSE #100  
 //SetGlobal("PS4_ferme","COM021",1) 

 CloseDoor("PS4")
 PlaySound("AMB_D04A")
   
 // Relance vérification 
 SetGlobalTimer("PS4_OUVERT","COM021",2) 
END



/*
// Le passage est ouvert
IF
  Range([ANYTHING],5)
  Global("PS_OUVERT2","COM021",0)
THEN
  RESPONSE #100
  SetGlobal("PS_OUVERT2","COM021",1)
  OpenDoor("PS4")
  PlaySound("GAM_21")
END

// Le passage est fermé
IF
  !Range([ANYTHING],5)
  Global("PS_OUVERT2","COM021",1)
THEN
  RESPONSE #100
  SetGlobal("PS_OUVERT2","COM021",0)
END
*/