// Gestion arrivée des PC ***********************************************************************************************************************************************
// Le but est de savoir quels sont les PLAYERS qui vont devoir se téléporter
IF
 AreaCheckObject("COM021",PLAYER1)
 Global("com021_P1","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("com021_P1","GLOBAL",1)
END

IF
 AreaCheckObject("COM021",PLAYER2)
 Global("com021_P2","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("com021_P2","GLOBAL",1)  
END

IF
 AreaCheckObject("COM021",PLAYER3)
 Global("com021_P3","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("com021_P3","GLOBAL",1)  
END

IF
 AreaCheckObject("COM021",PLAYER4)
 Global("com021_P4","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("com021_P4","GLOBAL",1)  
END

IF
 AreaCheckObject("COM021",PLAYER5)
 Global("com021_P5","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("com021_P5","GLOBAL",1)  
END

IF
 AreaCheckObject("COM021",PLAYER6)
 Global("com021_P6","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("com021_P6","GLOBAL",1)  
END
