// info signalant qu'une corde est présente. Elle permettrait de remonter au niveau supp.
IF
  Entered([PC]) 
  InPartySlot(LastTrigger,0) // Player1 
THEN
  RESPONSE #100
  
  Createcreature("COCORD",[480.359],10)
  ActionOverride("COCORD",StartDialog("COBCOR1",PLAYER1)
END

IF
  Entered([PC])   
  InPartySlot(LastTrigger,1) // Player2
THEN
  RESPONSE #100
  
  Createcreature("COCORD",[480.359],10)
  ActionOverride("COCORD",StartDialog("COBCOR1",PLAYER2)
END

IF
  Entered([PC])   
  InPartySlot(LastTrigger,2) // Player3
THEN
  RESPONSE #100
  
  Createcreature("COCORD",[480.359],10)
  ActionOverride("COCORD",StartDialog("COBCOR1",PLAYER3)
END

IF
  Entered([PC])   
  InPartySlot(LastTrigger,3) // Player4
THEN
  RESPONSE #100
  
  Createcreature("COCORD",[480.359],10)
  ActionOverride("COCORD",StartDialog("COBCOR1",PLAYER4)
END

IF
  Entered([PC])   
  InPartySlot(LastTrigger,4) // Player5
THEN
  RESPONSE #100
  
  Createcreature("COCORD",[480.359],10)
  ActionOverride("COCORD",StartDialog("COBCOR1",PLAYER5)
END

IF
  Entered([PC])   
  InPartySlot(LastTrigger,5) // Player6
THEN
  RESPONSE #100
  
  Createcreature("COCORD",[480.359],10)
  ActionOverride("COCORD",StartDialog("COBCOR1",PLAYER6)
END
