IF
 Areacheck("COM022")
 Clicked([ANYONE])
 Global("CLK_COM022_textSCR","GLOBAL",0)
 Global("COM022_23_textSCR","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("CLK_COM022_textSCR","GLOBAL",1)

END

IF
 Areacheck("COM023")
 Clicked([ANYONE])
 Global("CLK_COM023_textSCR","GLOBAL",0)
 Global("COM022_23_textSCR","GLOBAL",0)
THEN
 RESPONSE #100
 SetGlobal("CLK_COM023_textSCR","GLOBAL",1)
 
END

