// Départ TP vers un niveau aléatoire
IF
 Global("com017_P1","GLOBAL",1)
THEN
  RESPONSE #100
  SetGlobal("com017_P1","GLOBAL",2)
  SetInterrupt(FALSE)  
   Wait(1)
   ActionOverride(PLAYER1,LeaveAreaLUA("COM018","",[870.1240],10))
   ActionOverride(PLAYER1,ChangeAIScript("",RACE)) 
  SetInterrupt(TRUE)  
END

IF
 Global("com017_P2","GLOBAL",1)
THEN
  RESPONSE #100
  SetGlobal("com017_P2","GLOBAL",2)
  SetInterrupt(FALSE)
   Wait(1)
   ActionOverride(PLAYER2,LeaveAreaLUA("COM018","",[870.1240],10))
   ACTIONOVERRIDE(PLAYER2,ChangeAIScript("",RACE))
  SetInterrupt(TRUE)
END

IF
  Global("com017_P3","GLOBAL",1)
THEN
  RESPONSE #100
  SetGlobal("com017_P3","GLOBAL",2)
  SetInterrupt(FALSE) 
   Wait(1)
   ActionOverride(PLAYER3,LeaveAreaLUA("COM018","",[870.1240],10))
   ActionOverride(PLAYER3,ChangeAIScript("",RACE)) 
  SetInterrupt(TRUE) 
END

IF
 Global("com017_P4","GLOBAL",1)
THEN
  RESPONSE #100
  SetGlobal("com017_P4","GLOBAL",2)
  SetInterrupt(FALSE) 
   Wait(1)
   ActionOverride(PLAYER4,LeaveAreaLUA("COM018","",[870.1240],10))
   ActionOverride(PLAYER4,ChangeAIScript("",RACE))
  SetInterrupt(TRUE)  
END

IF
 Global("com017_P5","GLOBAL",1)
THEN
  RESPONSE #100
  SetGlobal("com017_P5","GLOBAL",2)
  SetInterrupt(FALSE) 
  Wait(1)
  ActionOverride(PLAYER5,LeaveAreaLUA("COM018","",[870.1240],10))
  ActionOverride(PLAYER5,ChangeAIScript("",RACE))
  SetInterrupt(TRUE) 
END

IF
  Global("com017_P6","GLOBAL",1)
THEN
  RESPONSE #100
  SetGlobal("com017_P6","GLOBAL",2)
  SetInterrupt(FALSE)  
   Wait(1)
   ActionOverride(PLAYER6,LeaveAreaLUA("COM018","",[870.1240],10))
   ActionOverride(PLAYER6,ChangeAIScript("",RACE))
  SetInterrupt(TRUE) 
END


/* V1
// Départ TP vers la salle n°1 de l'épreuve
IF
 Global("TimeTP_17","GLOBAL",1)
THEN
  RESPONSE #100
  //Createcreature("MINSC",[3700.600],10) 

  ActionOverride(PLAYER1,LeaveAreaLUA("COM018","",[870.1240],10))
  ActionOverride(PLAYER1,ChangeAIScript("",RACE))
END

*/