// Kael entame le dialogue ****************************************************************************************************************************************************
// 1iere rencontre avec KAEL
IF
 Global("KAEL_rencontre","COM022",0)
 Global("Kael_vaincu","COM022",0)
 See([PC])
 Range([PC],10)
THEN
 RESPONSE #100 
 SetGlobal("KAEL_rencontre","COM022",1)
 SetInterrupt(TRUE)
  ActionOverride("COKAEL",FaceObject([PC]))
  SmallWait(20)
  StartDialogueNoSet([PC])  
 SetInterrupt(FALSE)
END


// Quête de l'artéfact et Kael inconnu ****************************************************************************************************
IF
 Global("KAEL_quete_artefact","COM022",1)
 Global("KAEL_reconnu","COM022",0)
THEN
 RESPONSE #100 
 SetGlobal("KAEL_quete_artefact","COM022",2)
 AddJournalEntry(@300,QUEST)
END

// Quête de l'artéfact et Kael reconnu
IF
 Global("KAEL_quete_artefact","COM022",1)
 Global("KAEL_reconnu","COM022",1)
THEN
 RESPONSE #100 
 SetGlobal("KAEL_quete_artefact","COM022",2)
 AddJournalEntry(@302,QUEST)
END

// CUTSCENE création de l'artefact Horreur guerrière
IF
Global("KAEL_artefact_creation","COM022",2)
THEN
 RESPONSE #100 
 SetGlobal("KAEL_artefact_creation","COM022",3)

 StartCutSceneMode()
 StartCutScene("COCS022A") 
END

// Artefact créé
IF
 See(PLAYER1)
 Global("KAEL_artefact_creation","COM022",4)
THEN
 RESPONSE #100 
 SetGlobal("KAEL_artefact_creation","COM022",5)

 StartDialogueNoSet(PLAYER1)  
END

// Quête artefact réalisée
 // Kael non reconnu
IF
 Global("KAEL_reconnu","COM022",0)
 Global("KAEL_artefact_creation","COM022",6)
 Global("KAEL_quete_artefact","COM022",2)
THEN
 RESPONSE #100 
 SetGlobal("KAEL_quete_artefact","COM022",3)

 EraseJournalEntry(@300)
 AddJournalEntry(@301,QUEST_DONE) 

 AddexperienceParty(1000)    
END

// Quête artefact réalisée
 // Kael reconnu
IF
 Global("KAEL_reconnu","COM022",1)
 Global("KAEL_artefact_creation","COM022",6)
 Global("KAEL_quete_artefact","COM022",2)
THEN
 RESPONSE #100 
 SetGlobal("KAEL_quete_artefact","COM022",3)

 EraseJournalEntry(@302)
 AddJournalEntry(@303,QUEST_DONE) 

 AddexperienceParty(1000)   
 GiveItem("MISCP64",PLAYER1)
END

// Kael allié et les autres Boss sont éliminés: dernier dialogue ****************************************************************************************************
IF
 Global("NB_boss_dead","COM024",6)
 Global("CO_KAEL_ALLIE","GLOBAL",1)
 Global("KAEL_FIN","COM024",0)
THEN
 RESPONSE #100
 SetGlobal("KAEL_FIN","COM024",1)
 //Createcreature("MINSC",[1400.720],10)
 //Createcreature("MINSC",[1400.720],10)
 
 SetInterrupt(FALSE)
  FaceObject(PLAYER1)
  SmallWait(20) 
  StartDialogueNoSet(PLAYER1)
 SetInterrupt(TRUE)
END








/*
// Kael va être vaincu et sacrifice accepté ************************************************************************************************************************************************************
IF
  Global("Kael_vaincu","COM022",0) 
  Global("Kael_sacrifice","COM022",7)
  OR(2)
   HpPercentLT("COKAEL",20)
   Die()
THEN
  RESPONSE #100
  SetGlobal("Kael_vaincu","COM022",1)
  
  // larme de sang
  CreateItem("MISCP40",0,0,0)
  DropInventory() 
  
  //StartDialogueNoSet([PC])  
END

// Kael est vaincu et sacrifice refusé
IF
  Global("Kael_vaincu","COM022",0) 
  Global("Kael_sacrifice","COM022",1)
  OR(2)
   HpPercentLT("COKAEL",50)
   Die()
THEN
  RESPONSE #100
  SetGlobal("Kael_vaincu","COM022",1)
  
  ChangeEnemyAlly(Myself,NEUTRAL) // Arrêt du combat  
END

// Kael est vaincu et sacrifice refusé
IF
  Global("Kael_vaincu","COM022",1) 
  Global("Kael_sacrifice","COM022",1)
  OR(2)
   HpPercentLT("COKAEL",50)
   Die()
THEN
  RESPONSE #100
  SetGlobal("Kael_vaincu","COM022",2)
  
  Setinterrupt(FALSE)
  StartDialogueNoSet([PC])  
  
  // larme de sang
  CreateItem("MISCP40",0,0,0)
  DropInventory() 
 
  CreateVisualEffectObject("CODEATH",myself) 
  smallWait(10)
  Setinterrupt(TRUE)
  
  Deactivate(myself)
  Wait(1)
  ActionOverride(myself,DestroySelf()) 
  
END
*/








/*
IF
  Global("Kael_vaincu","COM022",3) 
THEN
  RESPONSE #100
  
  ActionOverride("COKAEL",CreateItem("MISCP40",0,0,0))
  CreateVisualEffectObject("SPFDEATH","COKAEL") 
  PlayDead(20)
  Deactivate("COKAEL")    
  Wait(2)
  ActionOverride("COKAEL",DestroySelf())  
END

// Kael a effectué le sacrifice: la grille s'ouvre **************************************************************************************************************************
IF
 Global("Kael_sacrifice","COM022",8)
THEN
 RESPONSE #100
 SetGlobal("Kael_sacrifice","COM022",9)
 
 OpenDoor("GRILLE1") 
END


// NON UTILE: il n'y a plus de sacrifice
// NB pnj sur la carte (groupe potentiellement séparé) **********************************************************************************************************
IF
  Global("KAEL_rencontre","COM022",0) 
  See(PLAYER1)
THEN
  RESPONSE #100
  SetGlobal("KAEL_rencontre","COM022",1)
END

IF 
 Global("KAEL_rencontre","COM022",1)
 AreaCheckObject("COM022",Player2)
 Global("COM022_PLAYER2","COM022",0)
THEN
 RESPONSE #100
 SetGlobal("COM022_PLAYER2","COM022",1)
 IncrementGlobal("COM022_NB_PLAYER","COM022",1) 
 SetGlobal("COM022_PLAYER2","COM022",1) 
END

IF 
 Global("KAEL_rencontre","COM022",1)
 AreaCheckObject("COM022",Player3)
 Global("COM022_PLAYER3","COM022",0)
THEN
 RESPONSE #100
 SetGlobal("COM022_PLAYER3","COM022",1)
 IncrementGlobal("COM022_NB_PLAYER","COM022",1) 
 SetGlobal("COM022_PLAYER3","COM022",1) 
END

IF 
 Global("KAEL_rencontre","COM022",1)
 AreaCheckObject("COM022",Player4)
 Global("COM022_PLAYER4","COM022",0)
THEN
 RESPONSE #100
 SetGlobal("COM022_PLAYER4","COM022",1)
 IncrementGlobal("COM022_NB_PLAYER","COM022",1) 
 SetGlobal("COM022_PLAYER4","COM022",1) 
END

IF 
 Global("KAEL_rencontre","COM022",1)
 AreaCheckObject("COM022",Player5)
 Global("COM022_PLAYER5","COM022",0)
THEN
 RESPONSE #100
 SetGlobal("COM022_PLAYER5","COM022",1)
 IncrementGlobal("COM022_NB_PLAYER","COM022",1) 
 SetGlobal("COM022_PLAYER5","COM022",1) 
END

IF 
 Global("KAEL_rencontre","COM022",1)
 AreaCheckObject("COM022",Player6)
 Global("COM022_PLAYER6","COM022",0)
THEN
 RESPONSE #100
 SetGlobal("COM022_PLAYER6","COM022",1)
 IncrementGlobal("COM022_NB_PLAYER","COM022",1) 
 SetGlobal("COM022_PLAYER6","COM022",1) 
END

// Kael est sévèrement blessé: la fontaine soigne Kael ***********************************************************************************************************************
IF
  HpPercentLT("COKAEL",90)
  Global("KAEL_blesse","COM022",0)  
THEN
  RESPONSE #100  
  SetGlobal("KAEL_blesse","COM022",1) 
  
  TriggerActivation("COT022F",TRUE) 
END
*/

