IF
 !See([PC])
 !See("COTAGUAR")
 !ActuallyInCombat()
THEN
 RESPONSE #100
 RandomWalk()
 Continue()
END

// Urglite va ête vaincue et Taguar est présent
IF
 HPPercentLT("COURGLIT",25)
 Global("URGLIT_meurt","COM021",0)
 Global("TAGUAR_meurt","COM021",0)
THEN
 RESPONSE #100
 SetGlobal("URGLIT_meurt","COM021",1)
 ClearAllActions()

//CreateCreature("MINSC",[1120.400],6) 

 StartDialogue("COURGLIT","COTAGUAR")
END

IF
 Global("URGLIT_meurt","COM021",2)
THEN
 RESPONSE #100
 SetGlobal("URGLIT_meurt","COM021",3)
 ClearAllActions()
 
  ActionOverride("COTAGUAR",ChangeAIScript("COTAGUA2",DEFAULT))
  CreateVisualEffectObject("SPFDEATH","COURGLIT") 
  PlayDead(20)
  CreateItem("RINGP11",0,0,0)
  DropInventory() 
  Deactivate("COURGLIT")  
  Wait(2)
  ActionOverride("COURGLIT",DestroySelf())
END


// Renouvellement des sorts
IF
  See("COTAGUAR")
  GLOBAL("Urglit_range1","LOCALS",0)
THEN
  RESPONSE #100
  SETGLOBAL("Urglit_range1","LOCALS",1)
  SetGlobalTimer("Urglit_SPELL","LOCALS",1)
END

// Combat corps à corps
IF
 See("COTAGUAR")
 GlobalTimerExpired("Urglit_SPELL","LOCALS")
 Range("COTAGUAR",5)
 GlobalLT("Urglit_SPELL_range1","LOCALS",5)
THEN

  // Cône de glace
  REsPONSE #100
  SetGlobalTimer("Urglit_SPELL","LOCALS",6)
  ForceSpell("COTAGUAR",WIZARD_CONE_OF_COLD)
  IncrementGlobal("Urglit_SPELL_range1","LOCALS",1)
  
  // Toucher glacial
  REsPONSE #100
  SetGlobalTimer("Urglit_SPELL","LOCALS",6)
  ForceSpell("COTAGUAR",WIZARD_CHILL_TOUCH)
  IncrementGlobal("Urglit_SPELL_range1","LOCALS",1)
  AttackOneRound("COTAGUAR")
  AttackOneRound("COTAGUAR")
  
  // Souffle glacial  
  REsPONSE #100
  SetGlobalTimer("Urglit_SPELL","LOCALS",6)
  //ForceSpell("COTAGUAR",BREATH_SOURCE_COLD)
  ForceSpellRes("COBREC1",NearestEnemyOf(Myself))
  IncrementGlobal("Urglit_SPELL_range1","LOCALS",1)
  
  // Blizzard
END

// Combat à distance
IF
 See("COTAGUAR")
 GlobalTimerExpired("Urglit_SPELL","LOCALS")
 !Range("COTAGUAR",5)
 GlobalLT("Urglit_SPELL_rangeX","LOCALS",5)
 !StateCheck(myself,STATE_HASTED)
THEN
  // Tempête de glace
  REsPONSE #100
  SetGlobalTimer("Urglit_SPELL","LOCALS",6)
  ForceSpell("COTAGUAR",WIZARD_ICE_STORM)
  IncrementGlobal("Urglit_SPELL_rangeX","LOCALS",1)
  
  // Projectile de glace
  REsPONSE #100
  SetGlobalTimer("Urglit_SPELL","LOCALS",6)
  //ForceSpell("COTAGUAR",SHARD_COLD)
  IncrementGlobal("Urglit_SPELL_rangeX","LOCALS",1)
  ForceSpellRes("COSHAC1",NearestEnemyOf(Myself))
  
  // Rapidité et attaque
  REsPONSE #100
  SetGlobalTimer("Urglit_SPELL","LOCALS",6)
  ForceSpell("COTAGUAR",WIZARD_HASTE)
  IncrementGlobal("Urglit_SPELL_rangeX","LOCALS",1)
  MoveViewObject("COTAGUAR",STANDARD)
END

// plus de sorts:corps à corps
IF
 See("COTAGUAR")
THEN
 RESPONSE #100
 Attack("COTAGUAR") 
END

