// Ekilis brule les restes de Massena et Massena disparait
IF
  True()
THEN
  RESPONSE #100
  CutSceneId(Player1)
  
  ActionOverride("COEKILIS",TakePartyItem("SKELP01"))
  
  FadeTOColor([20.0],0)  
  WAIT(1)
   
  // Placement du groupe près de la grille 
  Activate("COMASSE1")
  ActionOverride(player2,JumpToPoint([1796.814]))
  ActionOverride(player3,JumpToPoint([2022.798]))
  ActionOverride(player4,JumpToPoint([1846.849]))
  ActionOverride(player5,JumpToPoint([1841.760]))
  ActionOverride(player6,JumpToPoint([1903.847]))
  MultiPlayerSync()
  ActionOverride("COEKILIS",JumpToPoint([1902.790]))
  JumpToPoint([1967.830])
  FaceObject("COEKILIS")
  
  //Wait(3)
  FadeFromColor([20.0],0)
  
  //SetInterrupt(FALSE)
  Wait(3)
  DisplayStringHead("COMASSE1",@5) 
  ActionOverride("COEKILIS",DestroyItem("SKELP01"))
  Wait(1)
  ActionOverride("COEKILIS",ForceSpell("COMASSE1","CLERIC_FLAME_STRIKE"))
  Wait(5)
  DisplayStringHead("COMASSE1",@6)
  ActionOverride("COMASSE1",DropInventory())
  Wait(1)
  DeActivate("COMASSE1") 
  Wait(5)
  DisplayStringHead("COEKILIS",@7)  
  Wait(1)
  SetGlobal("Massena_reste_brule","GLOBAL",3)  
  
  // mise à jour journal
  EraseJournalEntry(@63)
  EraseJournalEntry(@64)
  EraseJournalEntry(@65)
  EraseJournalEntry(@66)
  EraseJournalEntry(@67)
  AddJournalEntry(@69,QUEST_DONE)
  
  EndCutSceneMode() 
END

